/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AadhaarLanguage
 */
class AadhaarLanguageTest {
    private final AadhaarLanguage model = new AadhaarLanguage();

    /**
     * Model tests for AadhaarLanguage
     */
    @Test
    void testAadhaarLanguage() {
        // TODO: test AadhaarLanguage
    }

    /**
     * Test the property 'languageCode'
     */
    @Test
    void languageCodeTest() {
        // TODO: test languageCode
    }

    /**
     * Test the property 'languageName'
     */
    @Test
    void languageNameTest() {
        // TODO: test languageName
    }

}
