/*
 * Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AttachmentAccessKeys
 */
class AttachmentAccessKeysTest {
    private final AttachmentAccessKeys model = new AttachmentAccessKeys();

    /**
     * Model tests for AttachmentAccessKeys
     */
    @Test
    void testAttachmentAccessKeys() {
        // TODO: test AttachmentAccessKeys
    }

    /**
     * Test the property 'selfie'
     */
    @Test
    void selfieTest() {
        // TODO: test selfie
    }

    /**
     * Test the property 'documentFront'
     */
    @Test
    void documentFrontTest() {
        // TODO: test documentFront
    }

    /**
     * Test the property 'documentBack'
     */
    @Test
    void documentBackTest() {
        // TODO: test documentBack
    }

    /**
     * Test the property 'documentPortrait'
     */
    @Test
    void documentPortraitTest() {
        // TODO: test documentPortrait
    }

}
