/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.trinsic.api.models.ColombiaExpeditionPlace;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ColombiaCcProviderOutput
 */
class ColombiaCcProviderOutputTest {
    private final ColombiaCcProviderOutput model = new ColombiaCcProviderOutput();

    /**
     * Model tests for ColombiaCcProviderOutput
     */
    @Test
    void testColombiaCcProviderOutput() {
        // TODO: test ColombiaCcProviderOutput
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'givenName'
     */
    @Test
    void givenNameTest() {
        // TODO: test givenName
    }

    /**
     * Test the property 'familyName'
     */
    @Test
    void familyNameTest() {
        // TODO: test familyName
    }

    /**
     * Test the property 'dateOfBirth'
     */
    @Test
    void dateOfBirthTest() {
        // TODO: test dateOfBirth
    }

    /**
     * Test the property 'sex'
     */
    @Test
    void sexTest() {
        // TODO: test sex
    }

    /**
     * Test the property 'isAlive'
     */
    @Test
    void isAliveTest() {
        // TODO: test isAlive
    }

    /**
     * Test the property 'documentNumber'
     */
    @Test
    void documentNumberTest() {
        // TODO: test documentNumber
    }

    /**
     * Test the property 'expeditionDate'
     */
    @Test
    void expeditionDateTest() {
        // TODO: test expeditionDate
    }

    /**
     * Test the property 'expeditionPlace'
     */
    @Test
    void expeditionPlaceTest() {
        // TODO: test expeditionPlace
    }

    /**
     * Test the property 'arrayName'
     */
    @Test
    void arrayNameTest() {
        // TODO: test arrayName
    }

}
