/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ConnectIdBeneficiaryAccount
 */
class ConnectIdBeneficiaryAccountTest {
    private final ConnectIdBeneficiaryAccount model = new ConnectIdBeneficiaryAccount();

    /**
     * Model tests for ConnectIdBeneficiaryAccount
     */
    @Test
    void testConnectIdBeneficiaryAccount() {
        // TODO: test ConnectIdBeneficiaryAccount
    }

    /**
     * Test the property 'beneficiaryName'
     */
    @Test
    void beneficiaryNameTest() {
        // TODO: test beneficiaryName
    }

    /**
     * Test the property 'accountBankStateBranch'
     */
    @Test
    void accountBankStateBranchTest() {
        // TODO: test accountBankStateBranch
    }

    /**
     * Test the property 'accountNumber'
     */
    @Test
    void accountNumberTest() {
        // TODO: test accountNumber
    }

    /**
     * Test the property 'trustFramework'
     */
    @Test
    void trustFrameworkTest() {
        // TODO: test trustFramework
    }

}
