/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateMdlExchangeResponse
 */
class CreateMdlExchangeResponseTest {
    private final CreateMdlExchangeResponse model = new CreateMdlExchangeResponse();

    /**
     * Model tests for CreateMdlExchangeResponse
     */
    @Test
    void testCreateMdlExchangeResponse() {
        // TODO: test CreateMdlExchangeResponse
    }

    /**
     * Test the property 'exchangeId'
     */
    @Test
    void exchangeIdTest() {
        // TODO: test exchangeId
    }

    /**
     * Test the property 'requestObjectBase64Url'
     */
    @Test
    void requestObjectBase64UrlTest() {
        // TODO: test requestObjectBase64Url
    }

    /**
     * Test the property 'exchangeContext'
     */
    @Test
    void exchangeContextTest() {
        // TODO: test exchangeContext
    }

}
