/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.trinsic.api.models.AadhaarClaims;
import id.trinsic.api.models.AadhaarLocalizedClaims;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DigilockerAadhaarProviderOutput
 */
class DigilockerAadhaarProviderOutputTest {
    private final DigilockerAadhaarProviderOutput model = new DigilockerAadhaarProviderOutput();

    /**
     * Model tests for DigilockerAadhaarProviderOutput
     */
    @Test
    void testDigilockerAadhaarProviderOutput() {
        // TODO: test DigilockerAadhaarProviderOutput
    }

    /**
     * Test the property 'documentType'
     */
    @Test
    void documentTypeTest() {
        // TODO: test documentType
    }

    /**
     * Test the property 'documentSignatureValidated'
     */
    @Test
    void documentSignatureValidatedTest() {
        // TODO: test documentSignatureValidated
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'timeToLive'
     */
    @Test
    void timeToLiveTest() {
        // TODO: test timeToLive
    }

    /**
     * Test the property 'aadhaarNumberLastFour'
     */
    @Test
    void aadhaarNumberLastFourTest() {
        // TODO: test aadhaarNumberLastFour
    }

    /**
     * Test the property 'claims'
     */
    @Test
    void claimsTest() {
        // TODO: test claims
    }

    /**
     * Test the property 'localizedClaims'
     */
    @Test
    void localizedClaimsTest() {
        // TODO: test localizedClaims
    }

}
