/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FrenchNumeriqueGivenName
 */
class FrenchNumeriqueGivenNameTest {
    private final FrenchNumeriqueGivenName model = new FrenchNumeriqueGivenName();

    /**
     * Model tests for FrenchNumeriqueGivenName
     */
    @Test
    void testFrenchNumeriqueGivenName() {
        // TODO: test FrenchNumeriqueGivenName
    }

    /**
     * Test the property 'fullGivenName'
     */
    @Test
    void fullGivenNameTest() {
        // TODO: test fullGivenName
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'middleName'
     */
    @Test
    void middleNameTest() {
        // TODO: test middleName
    }

}
