/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IndonesiaDukcapilMatchInput
 */
class IndonesiaDukcapilMatchInputTest {
    private final IndonesiaDukcapilMatchInput model = new IndonesiaDukcapilMatchInput();

    /**
     * Model tests for IndonesiaDukcapilMatchInput
     */
    @Test
    void testIndonesiaDukcapilMatchInput() {
        // TODO: test IndonesiaDukcapilMatchInput
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'dateOfBirth'
     */
    @Test
    void dateOfBirthTest() {
        // TODO: test dateOfBirth
    }

    /**
     * Test the property 'nikIdNumber'
     */
    @Test
    void nikIdNumberTest() {
        // TODO: test nikIdNumber
    }

    /**
     * Test the property 'email'
     */
    @Test
    void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'selfieImage'
     */
    @Test
    void selfieImageTest() {
        // TODO: test selfieImage
    }

    /**
     * Test the property 'documentImage'
     */
    @Test
    void documentImageTest() {
        // TODO: test documentImage
    }

    /**
     * Test the property 'consentGivenAt'
     */
    @Test
    void consentGivenAtTest() {
        // TODO: test consentGivenAt
    }

}
