/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ItsmeProviderOutput
 */
class ItsmeProviderOutputTest {
    private final ItsmeProviderOutput model = new ItsmeProviderOutput();

    /**
     * Model tests for ItsmeProviderOutput
     */
    @Test
    void testItsmeProviderOutput() {
        // TODO: test ItsmeProviderOutput
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'dateOfBirth'
     */
    @Test
    void dateOfBirthTest() {
        // TODO: test dateOfBirth
    }

    /**
     * Test the property 'hashedNationalRegisterNumber'
     */
    @Test
    void hashedNationalRegisterNumberTest() {
        // TODO: test hashedNationalRegisterNumber
    }

    /**
     * Test the property 'nationalRegisterNumber'
     */
    @Test
    void nationalRegisterNumberTest() {
        // TODO: test nationalRegisterNumber
    }

}
