/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for KenyaNidBiometric2Input
 */
class KenyaNidBiometric2InputTest {
    private final KenyaNidBiometric2Input model = new KenyaNidBiometric2Input();

    /**
     * Model tests for KenyaNidBiometric2Input
     */
    @Test
    void testKenyaNidBiometric2Input() {
        // TODO: test KenyaNidBiometric2Input
    }

    /**
     * Test the property 'idNumber'
     */
    @Test
    void idNumberTest() {
        // TODO: test idNumber
    }

    /**
     * Test the property 'livenessImages'
     */
    @Test
    void livenessImagesTest() {
        // TODO: test livenessImages
    }

    /**
     * Test the property 'testSelfie'
     */
    @Test
    void testSelfieTest() {
        // TODO: test testSelfie
    }

}
