/*
 * Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for KnownAddress
 */
class KnownAddressTest {
    private final KnownAddress model = new KnownAddress();

    /**
     * Model tests for KnownAddress
     */
    @Test
    void testKnownAddress() {
        // TODO: test KnownAddress
    }

    /**
     * Test the property 'line1'
     */
    @Test
    void line1Test() {
        // TODO: test line1
    }

    /**
     * Test the property 'line2'
     */
    @Test
    void line2Test() {
        // TODO: test line2
    }

    /**
     * Test the property 'line3'
     */
    @Test
    void line3Test() {
        // TODO: test line3
    }

    /**
     * Test the property 'city'
     */
    @Test
    void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'state'
     */
    @Test
    void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'country'
     */
    @Test
    void countryTest() {
        // TODO: test country
    }

}
