/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.trinsic.api.models.MdlOutputCertificateData;
import id.trinsic.api.models.MdlOutputFieldData;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MdlOutput
 */
class MdlOutputTest {
    private final MdlOutput model = new MdlOutput();

    /**
     * Model tests for MdlOutput
     */
    @Test
    void testMdlOutput() {
        // TODO: test MdlOutput
    }

    /**
     * Test the property 'iacaRootCertificate'
     */
    @Test
    void iacaRootCertificateTest() {
        // TODO: test iacaRootCertificate
    }

    /**
     * Test the property 'documentSignerCertificate'
     */
    @Test
    void documentSignerCertificateTest() {
        // TODO: test documentSignerCertificate
    }

    /**
     * Test the property 'documentType'
     */
    @Test
    void documentTypeTest() {
        // TODO: test documentType
    }

    /**
     * Test the property 'nameSpaces'
     */
    @Test
    void nameSpacesTest() {
        // TODO: test nameSpaces
    }

}
