/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.trinsic.api.models.PeruDniAddress;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PeruDniProviderOutput
 */
class PeruDniProviderOutputTest {
    private final PeruDniProviderOutput model = new PeruDniProviderOutput();

    /**
     * Model tests for PeruDniProviderOutput
     */
    @Test
    void testPeruDniProviderOutput() {
        // TODO: test PeruDniProviderOutput
    }

    /**
     * Test the property 'address'
     */
    @Test
    void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'arrayName'
     */
    @Test
    void arrayNameTest() {
        // TODO: test arrayName
    }

    /**
     * Test the property 'civilStatus'
     */
    @Test
    void civilStatusTest() {
        // TODO: test civilStatus
    }

    /**
     * Test the property 'dateOfBirth'
     */
    @Test
    void dateOfBirthTest() {
        // TODO: test dateOfBirth
    }

    /**
     * Test the property 'documentNumber'
     */
    @Test
    void documentNumberTest() {
        // TODO: test documentNumber
    }

    /**
     * Test the property 'documentType'
     */
    @Test
    void documentTypeTest() {
        // TODO: test documentType
    }

    /**
     * Test the property 'expeditionDate'
     */
    @Test
    void expeditionDateTest() {
        // TODO: test expeditionDate
    }

    /**
     * Test the property 'expirationDate'
     */
    @Test
    void expirationDateTest() {
        // TODO: test expirationDate
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'maternalLastName'
     */
    @Test
    void maternalLastNameTest() {
        // TODO: test maternalLastName
    }

    /**
     * Test the property 'paternalLastName'
     */
    @Test
    void paternalLastNameTest() {
        // TODO: test paternalLastName
    }

    /**
     * Test the property 'sex'
     */
    @Test
    void sexTest() {
        // TODO: test sex
    }

    /**
     * Test the property 'ubigeoReniec'
     */
    @Test
    void ubigeoReniecTest() {
        // TODO: test ubigeoReniec
    }

    /**
     * Test the property 'verificationDigit'
     */
    @Test
    void verificationDigitTest() {
        // TODO: test verificationDigit
    }

}
