/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PeruDniAddress
 */
class PeruDniAddressTest {
    private final PeruDniAddress model = new PeruDniAddress();

    /**
     * Model tests for PeruDniAddress
     */
    @Test
    void testPeruDniAddress() {
        // TODO: test PeruDniAddress
    }

    /**
     * Test the property 'region'
     */
    @Test
    void regionTest() {
        // TODO: test region
    }

    /**
     * Test the property 'province'
     */
    @Test
    void provinceTest() {
        // TODO: test province
    }

    /**
     * Test the property 'district'
     */
    @Test
    void districtTest() {
        // TODO: test district
    }

}
