/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.trinsic.api.models.SubProviderMetadata;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProviderInformation
 */
class ProviderInformationTest {
    private final ProviderInformation model = new ProviderInformation();

    /**
     * Model tests for ProviderInformation
     */
    @Test
    void testProviderInformation() {
        // TODO: test ProviderInformation
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'logoUrl'
     */
    @Test
    void logoUrlTest() {
        // TODO: test logoUrl
    }

    /**
     * Test the property 'subtext'
     */
    @Test
    void subtextTest() {
        // TODO: test subtext
    }

    /**
     * Test the property 'providerId'
     */
    @Test
    void providerIdTest() {
        // TODO: test providerId
    }

    /**
     * Test the property 'providerDisplayName'
     */
    @Test
    void providerDisplayNameTest() {
        // TODO: test providerDisplayName
    }

    /**
     * Test the property 'providerLogo'
     */
    @Test
    void providerLogoTest() {
        // TODO: test providerLogo
    }

    /**
     * Test the property 'health'
     */
    @Test
    void healthTest() {
        // TODO: test health
    }

    /**
     * Test the property 'subProviders'
     */
    @Test
    void subProvidersTest() {
        // TODO: test subProviders
    }

}
