/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.trinsic.api.models.AppleWalletProviderOutput;
import id.trinsic.api.models.AudkenniProviderOutput;
import id.trinsic.api.models.AustriaHandySignaturProviderOutput;
import id.trinsic.api.models.BelgiumIdCardProviderOutput;
import id.trinsic.api.models.BoliviaCiProviderOutput;
import id.trinsic.api.models.ChinaResidentIdMatchOutput;
import id.trinsic.api.models.ColombiaCcProviderOutput;
import id.trinsic.api.models.ConnectIdProviderOutput;
import id.trinsic.api.models.CoteDIvoireNidLookup2ProviderOutput;
import id.trinsic.api.models.CzechMojeIdProviderOutput;
import id.trinsic.api.models.CzechiaMojeIdProviderOutput;
import id.trinsic.api.models.DigilockerAadhaarProviderOutput;
import id.trinsic.api.models.ElSalvadorDuiProviderOutput;
import id.trinsic.api.models.EstoniaIdCardProviderOutput;
import id.trinsic.api.models.FaydaProviderOutput;
import id.trinsic.api.models.FinlandIdCardProviderOutput;
import id.trinsic.api.models.FinnishTrustNetworkProviderOutput;
import id.trinsic.api.models.FranceIdentiteProviderOutput;
import id.trinsic.api.models.FrejaIndirectProviderOutput;
import id.trinsic.api.models.FrejaProviderOutput;
import id.trinsic.api.models.FrenchNumeriqueProviderOutput;
import id.trinsic.api.models.GoogleWalletProviderOutput;
import id.trinsic.api.models.GuatemalaCuiProviderOutput;
import id.trinsic.api.models.IndiaPanLookupProviderOutput;
import id.trinsic.api.models.ItsmeProviderOutput;
import id.trinsic.api.models.KenyaNidLookup2ProviderOutput;
import id.trinsic.api.models.KoreaTelcoMatchProviderOutput;
import id.trinsic.api.models.LaWalletProviderOutput;
import id.trinsic.api.models.LatviaEparakstsMobileProviderOutput;
import id.trinsic.api.models.LatviaEparakstsProviderOutput;
import id.trinsic.api.models.LithuaniaIdCardProviderOutput;
import id.trinsic.api.models.LloydsSmartIdProviderOutput;
import id.trinsic.api.models.MexicoCurpProviderOutput;
import id.trinsic.api.models.MitIdProviderOutput;
import id.trinsic.api.models.MobileIdProviderOutput;
import id.trinsic.api.models.NetherlandsIdinProviderOutput;
import id.trinsic.api.models.NigeriaNinLookup2ProviderOutput;
import id.trinsic.api.models.NorwegianBankIdProviderOutput;
import id.trinsic.api.models.OneIdProviderOutput;
import id.trinsic.api.models.PanamaCedulaProviderOutput;
import id.trinsic.api.models.PeruDniProviderOutput;
import id.trinsic.api.models.PhilippinesDigitalNidProviderOutput;
import id.trinsic.api.models.PhilippinesPhysicalNidProviderOutput;
import id.trinsic.api.models.PolandEdoAppProviderOutput;
import id.trinsic.api.models.PolandMobywatelMatchProviderOutput;
import id.trinsic.api.models.PolandMojeIdProviderOutput;
import id.trinsic.api.models.PortugalIdCardProviderOutput;
import id.trinsic.api.models.PostOfficeEasyIdProviderOutput;
import id.trinsic.api.models.SamsungWalletProviderOutput;
import id.trinsic.api.models.SerbiaIdCardProviderOutput;
import id.trinsic.api.models.SignzyIndiaAadhaarFetchProviderOutput;
import id.trinsic.api.models.SingpassLoginProviderOutput;
import id.trinsic.api.models.SingpassMyInfoProviderOutput;
import id.trinsic.api.models.SmartIdProviderOutput;
import id.trinsic.api.models.SpidProviderOutput;
import id.trinsic.api.models.SwedenBankIdProviderOutput;
import id.trinsic.api.models.UnitedKingdomEvisaProviderOutput;
import id.trinsic.api.models.YotiDeeplinkProviderOutput;
import id.trinsic.api.models.YotiProviderOutput;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProviderOutput
 */
class ProviderOutputTest {
    private final ProviderOutput model = new ProviderOutput();

    /**
     * Model tests for ProviderOutput
     */
    @Test
    void testProviderOutput() {
        // TODO: test ProviderOutput
    }

    /**
     * Test the property 'audkenni'
     */
    @Test
    void audkenniTest() {
        // TODO: test audkenni
    }

    /**
     * Test the property 'aAtHandySignaturLogin'
     */
    @Test
    void aAtHandySignaturLoginTest() {
        // TODO: test aAtHandySignaturLogin
    }

    /**
     * Test the property 'aBeIdLogin'
     */
    @Test
    void aBeIdLoginTest() {
        // TODO: test aBeIdLogin
    }

    /**
     * Test the property 'aEdoappEidLogin'
     */
    @Test
    void aEdoappEidLoginTest() {
        // TODO: test aEdoappEidLogin
    }

    /**
     * Test the property 'aEeWebEidLogin'
     */
    @Test
    void aEeWebEidLoginTest() {
        // TODO: test aEeWebEidLogin
    }

    /**
     * Test the property 'aFiIdLogin'
     */
    @Test
    void aFiIdLoginTest() {
        // TODO: test aFiIdLogin
    }

    /**
     * Test the property 'aFrejaEidLogin'
     */
    @Test
    void aFrejaEidLoginTest() {
        // TODO: test aFrejaEidLogin
    }

    /**
     * Test the property 'aItsmeLogin'
     */
    @Test
    void aItsmeLoginTest() {
        // TODO: test aItsmeLogin
    }

    /**
     * Test the property 'aLtIdLogin'
     */
    @Test
    void aLtIdLoginTest() {
        // TODO: test aLtIdLogin
    }

    /**
     * Test the property 'aLvEparakstsIdLogin'
     */
    @Test
    void aLvEparakstsIdLoginTest() {
        // TODO: test aLvEparakstsIdLogin
    }

    /**
     * Test the property 'aLvEparakstsMobileLogin'
     */
    @Test
    void aLvEparakstsMobileLoginTest() {
        // TODO: test aLvEparakstsMobileLogin
    }

    /**
     * Test the property 'aMojeid'
     */
    @Test
    void aMojeidTest() {
        // TODO: test aMojeid
    }

    /**
     * Test the property 'aPlMojeidLogin'
     */
    @Test
    void aPlMojeidLoginTest() {
        // TODO: test aPlMojeidLogin
    }

    /**
     * Test the property 'aPtIdLogin'
     */
    @Test
    void aPtIdLoginTest() {
        // TODO: test aPtIdLogin
    }

    /**
     * Test the property 'aRsIdLogin'
     */
    @Test
    void aRsIdLoginTest() {
        // TODO: test aRsIdLogin
    }

    /**
     * Test the property 'appleWallet'
     */
    @Test
    void appleWalletTest() {
        // TODO: test appleWallet
    }

    /**
     * Test the property 'australiaConnectId'
     */
    @Test
    void australiaConnectIdTest() {
        // TODO: test australiaConnectId
    }

    /**
     * Test the property 'boliviaCiLookup'
     */
    @Test
    void boliviaCiLookupTest() {
        // TODO: test boliviaCiLookup
    }

    /**
     * Test the property 'colombiaCcLookup'
     */
    @Test
    void colombiaCcLookupTest() {
        // TODO: test colombiaCcLookup
    }

    /**
     * Test the property 'coteDivoireNidLookup2'
     */
    @Test
    void coteDivoireNidLookup2Test() {
        // TODO: test coteDivoireNidLookup2
    }

    /**
     * Test the property 'elSalvadorDuiLookup'
     */
    @Test
    void elSalvadorDuiLookupTest() {
        // TODO: test elSalvadorDuiLookup
    }

    /**
     * Test the property 'czechRepublicMojeid'
     */
    @Test
    void czechRepublicMojeidTest() {
        // TODO: test czechRepublicMojeid
    }

    /**
     * Test the property 'denmarkMitid'
     */
    @Test
    void denmarkMitidTest() {
        // TODO: test denmarkMitid
    }

    /**
     * Test the property 'ethiopiaFayda'
     */
    @Test
    void ethiopiaFaydaTest() {
        // TODO: test ethiopiaFayda
    }

    /**
     * Test the property 'finnishTrustNetwork'
     */
    @Test
    void finnishTrustNetworkTest() {
        // TODO: test finnishTrustNetwork
    }

    /**
     * Test the property 'franceIdentite'
     */
    @Test
    void franceIdentiteTest() {
        // TODO: test franceIdentite
    }

    /**
     * Test the property 'franceIdentiteNumerique'
     */
    @Test
    void franceIdentiteNumeriqueTest() {
        // TODO: test franceIdentiteNumerique
    }

    /**
     * Test the property 'freja'
     */
    @Test
    void frejaTest() {
        // TODO: test freja
    }

    /**
     * Test the property 'googleWallet'
     */
    @Test
    void googleWalletTest() {
        // TODO: test googleWallet
    }

    /**
     * Test the property 'guatemalaCuiLookup'
     */
    @Test
    void guatemalaCuiLookupTest() {
        // TODO: test guatemalaCuiLookup
    }

    /**
     * Test the property 'panamaCedulaLookup'
     */
    @Test
    void panamaCedulaLookupTest() {
        // TODO: test panamaCedulaLookup
    }

    /**
     * Test the property 'indiaDigilockerAadhaar'
     */
    @Test
    void indiaDigilockerAadhaarTest() {
        // TODO: test indiaDigilockerAadhaar
    }

    /**
     * Test the property 'indiaDigilockerAadhaarFetch'
     */
    @Test
    void indiaDigilockerAadhaarFetchTest() {
        // TODO: test indiaDigilockerAadhaarFetch
    }

    /**
     * Test the property 'indiaPanLookup'
     */
    @Test
    void indiaPanLookupTest() {
        // TODO: test indiaPanLookup
    }

    /**
     * Test the property 'chinaResidentIdMatch'
     */
    @Test
    void chinaResidentIdMatchTest() {
        // TODO: test chinaResidentIdMatch
    }

    /**
     * Test the property 'italySpid'
     */
    @Test
    void italySpidTest() {
        // TODO: test italySpid
    }

    /**
     * Test the property 'kenyaNidLookup2'
     */
    @Test
    void kenyaNidLookup2Test() {
        // TODO: test kenyaNidLookup2
    }

    /**
     * Test the property 'koreaTelcoMatch'
     */
    @Test
    void koreaTelcoMatchTest() {
        // TODO: test koreaTelcoMatch
    }

    /**
     * Test the property 'lloydsSmartId'
     */
    @Test
    void lloydsSmartIdTest() {
        // TODO: test lloydsSmartId
    }

    /**
     * Test the property 'mexicoCurpLookup'
     */
    @Test
    void mexicoCurpLookupTest() {
        // TODO: test mexicoCurpLookup
    }

    /**
     * Test the property 'mobileId'
     */
    @Test
    void mobileIdTest() {
        // TODO: test mobileId
    }

    /**
     * Test the property 'nigeriaNinLookup2'
     */
    @Test
    void nigeriaNinLookup2Test() {
        // TODO: test nigeriaNinLookup2
    }

    /**
     * Test the property 'oneid'
     */
    @Test
    void oneidTest() {
        // TODO: test oneid
    }

    /**
     * Test the property 'peruDniLookup'
     */
    @Test
    void peruDniLookupTest() {
        // TODO: test peruDniLookup
    }

    /**
     * Test the property 'norwayBankid'
     */
    @Test
    void norwayBankidTest() {
        // TODO: test norwayBankid
    }

    /**
     * Test the property 'philippinesDigitalNationalIdQr'
     */
    @Test
    void philippinesDigitalNationalIdQrTest() {
        // TODO: test philippinesDigitalNationalIdQr
    }

    /**
     * Test the property 'philippinesPhysicalNationalIdQr'
     */
    @Test
    void philippinesPhysicalNationalIdQrTest() {
        // TODO: test philippinesPhysicalNationalIdQr
    }

    /**
     * Test the property 'polandMobywatelMatch'
     */
    @Test
    void polandMobywatelMatchTest() {
        // TODO: test polandMobywatelMatch
    }

    /**
     * Test the property 'postOfficeEasyid'
     */
    @Test
    void postOfficeEasyidTest() {
        // TODO: test postOfficeEasyid
    }

    /**
     * Test the property 'samsungWallet'
     */
    @Test
    void samsungWalletTest() {
        // TODO: test samsungWallet
    }

    /**
     * Test the property 'singpassLogin'
     */
    @Test
    void singpassLoginTest() {
        // TODO: test singpassLogin
    }

    /**
     * Test the property 'singpassMyinfo'
     */
    @Test
    void singpassMyinfoTest() {
        // TODO: test singpassMyinfo
    }

    /**
     * Test the property 'smartId'
     */
    @Test
    void smartIdTest() {
        // TODO: test smartId
    }

    /**
     * Test the property 'ukEvisaLookup'
     */
    @Test
    void ukEvisaLookupTest() {
        // TODO: test ukEvisaLookup
    }

    /**
     * Test the property 'swedenBankid'
     */
    @Test
    void swedenBankidTest() {
        // TODO: test swedenBankid
    }

    /**
     * Test the property 'usaLouisianaWallet'
     */
    @Test
    void usaLouisianaWalletTest() {
        // TODO: test usaLouisianaWallet
    }

    /**
     * Test the property 'netherlandsIdin'
     */
    @Test
    void netherlandsIdinTest() {
        // TODO: test netherlandsIdin
    }

    /**
     * Test the property 'yoti'
     */
    @Test
    void yotiTest() {
        // TODO: test yoti
    }

    /**
     * Test the property 'yotiDeeplink'
     */
    @Test
    void yotiDeeplinkTest() {
        // TODO: test yotiDeeplink
    }

}
