/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.trinsic.api.models.AadhaarInput;
import id.trinsic.api.models.BangladeshNidInput;
import id.trinsic.api.models.BrazilCpfCheckInput;
import id.trinsic.api.models.BrazilDigitalCnhInput;
import id.trinsic.api.models.IdinInput;
import id.trinsic.api.models.IndonesiaDukcapilMatchInput;
import id.trinsic.api.models.IndonesiaNikInput;
import id.trinsic.api.models.KenyaNidInput;
import id.trinsic.api.models.MexicoCurpInput;
import id.trinsic.api.models.MobileIdInput;
import id.trinsic.api.models.NigeriaNinInput;
import id.trinsic.api.models.PhilippineMatchInput;
import id.trinsic.api.models.PhilippineQRInput;
import id.trinsic.api.models.SmartIdInput;
import id.trinsic.api.models.SouthAfricaNidInput;
import id.trinsic.api.models.SpidInput;
import id.trinsic.api.models.TrinsicTestDatabaseLookupInput;
import id.trinsic.api.models.TrinsicTestSubProvidersInput;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProviderInput
 */
class ProviderInputTest {
    private final ProviderInput model = new ProviderInput();

    /**
     * Model tests for ProviderInput
     */
    @Test
    void testProviderInput() {
        // TODO: test ProviderInput
    }

    /**
     * Test the property 'indonesiaNik'
     */
    @Test
    void indonesiaNikTest() {
        // TODO: test indonesiaNik
    }

    /**
     * Test the property 'indonesiaDukcapilMatch'
     */
    @Test
    void indonesiaDukcapilMatchTest() {
        // TODO: test indonesiaDukcapilMatch
    }

    /**
     * Test the property 'mexicoCurp'
     */
    @Test
    void mexicoCurpTest() {
        // TODO: test mexicoCurp
    }

    /**
     * Test the property 'southAfricaNid'
     */
    @Test
    void southAfricaNidTest() {
        // TODO: test southAfricaNid
    }

    /**
     * Test the property 'kenyaNid'
     */
    @Test
    void kenyaNidTest() {
        // TODO: test kenyaNid
    }

    /**
     * Test the property 'nigeriaNin'
     */
    @Test
    void nigeriaNinTest() {
        // TODO: test nigeriaNin
    }

    /**
     * Test the property 'aadhaar'
     */
    @Test
    void aadhaarTest() {
        // TODO: test aadhaar
    }

    /**
     * Test the property 'bangladeshNationalId'
     */
    @Test
    void bangladeshNationalIdTest() {
        // TODO: test bangladeshNationalId
    }

    /**
     * Test the property 'brazilCpfCheck'
     */
    @Test
    void brazilCpfCheckTest() {
        // TODO: test brazilCpfCheck
    }

    /**
     * Test the property 'brazilDigitalCnh'
     */
    @Test
    void brazilDigitalCnhTest() {
        // TODO: test brazilDigitalCnh
    }

    /**
     * Test the property 'philippineMatch'
     */
    @Test
    void philippineMatchTest() {
        // TODO: test philippineMatch
    }

    /**
     * Test the property 'philippineQR'
     */
    @Test
    void philippineQRTest() {
        // TODO: test philippineQR
    }

    /**
     * Test the property 'smartId'
     */
    @Test
    void smartIdTest() {
        // TODO: test smartId
    }

    /**
     * Test the property 'mobileId'
     */
    @Test
    void mobileIdTest() {
        // TODO: test mobileId
    }

    /**
     * Test the property 'idin'
     */
    @Test
    void idinTest() {
        // TODO: test idin
    }

    /**
     * Test the property 'spid'
     */
    @Test
    void spidTest() {
        // TODO: test spid
    }

    /**
     * Test the property 'trinsicTestDatabaseLookup'
     */
    @Test
    void trinsicTestDatabaseLookupTest() {
        // TODO: test trinsicTestDatabaseLookup
    }

    /**
     * Test the property 'trinsicTestSubProviders'
     */
    @Test
    void trinsicTestSubProvidersTest() {
        // TODO: test trinsicTestSubProviders
    }

}
