/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SingpassLoginProviderOutput
 */
class SingpassLoginProviderOutputTest {
    private final SingpassLoginProviderOutput model = new SingpassLoginProviderOutput();

    /**
     * Model tests for SingpassLoginProviderOutput
     */
    @Test
    void testSingpassLoginProviderOutput() {
        // TODO: test SingpassLoginProviderOutput
    }

    /**
     * Test the property 'sub'
     */
    @Test
    void subTest() {
        // TODO: test sub
    }

    /**
     * Test the property 'accountType'
     */
    @Test
    void accountTypeTest() {
        // TODO: test accountType
    }

    /**
     * Test the property 'identityNumber'
     */
    @Test
    void identityNumberTest() {
        // TODO: test identityNumber
    }

    /**
     * Test the property 'countryOfIssuance'
     */
    @Test
    void countryOfIssuanceTest() {
        // TODO: test countryOfIssuance
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'email'
     */
    @Test
    void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'mobileNumber'
     */
    @Test
    void mobileNumberTest() {
        // TODO: test mobileNumber
    }

}
