/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api;

import id.trinsic.ApiException;
import id.trinsic.api.models.GetProviderResponse;
import id.trinsic.api.models.ListProvidersResponse;
import id.trinsic.api.models.ProblemDetails;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for ProvidersApi
 */
@Disabled
public class ProvidersApiTest {

    private final ProvidersApi api = new ProvidersApi();

    
    /**
     * Get Provider
     *
     * Get a single identity provider by ID, including its license status.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProviderTest() throws ApiException {
        String providerId = null;
        GetProviderResponse response = 
        api.getProvider(providerId);
        
        // TODO: test validations
    }
    
    /**
     * List Providers
     *
     * List all identity providers available to your Organization, including their license status.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listProvidersTest() throws ApiException {
        Boolean licensed = null;
        ListProvidersResponse response = 
        api.listProviders(licensed);
        
        // TODO: test validations
    }
    
}
