/*
 * Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api;

import id.trinsic.ApiException;
import id.trinsic.api.models.CancelSessionResponse;
import id.trinsic.api.models.CreateSessionRequest;
import id.trinsic.api.models.CreateSessionResponse;
import id.trinsic.api.models.FailureMessage;
import id.trinsic.api.models.GetSessionResponse;
import id.trinsic.api.models.GetSessionResultRequest;
import id.trinsic.api.models.GetSessionResultResponse;
import id.trinsic.api.models.ListSessionsResponse;
import id.trinsic.api.models.OrderDirection;
import id.trinsic.api.models.SessionOrdering;
import id.trinsic.api.models.ValidationResult;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for SessionsApi
 */
@Disabled
public class SessionsApiTest {

    private final SessionsApi api = new SessionsApi();

    
    /**
     * Cancel Session
     *
     * Cancel a Session by its ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cancelSessionTest() throws ApiException {
        String sessionId = null;
        CancelSessionResponse response = 
        api.cancelSession(sessionId);
        
        // TODO: test validations
    }
    
    /**
     * Create Session
     *
     * Create a Session to verify a user&#39;s identity
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSessionTest() throws ApiException {
        CreateSessionRequest createSessionRequest = null;
        CreateSessionResponse response = 
        api.createSession(createSessionRequest);
        
        // TODO: test validations
    }
    
    /**
     * Get Session
     *
     * Get a Session by its ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSessionTest() throws ApiException {
        String sessionId = null;
        GetSessionResponse response = 
        api.getSession(sessionId);
        
        // TODO: test validations
    }
    
    /**
     * Get Session Results
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSessionResultTest() throws ApiException {
        String sessionId = null;
        GetSessionResultRequest getSessionResultRequest = null;
        GetSessionResultResponse response = 
        api.getSessionResult(sessionId, getSessionResultRequest);
        
        // TODO: test validations
    }
    
    /**
     * List Sessions
     *
     * List Sessions created by your account
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listSessionsTest() throws ApiException {
        SessionOrdering orderBy = null;
        OrderDirection orderDirection = null;
        Integer pageSize = null;
        Integer page = null;
        ListSessionsResponse response = 
        api.listSessions(orderBy, orderDirection, pageSize, page);
        
        // TODO: test validations
    }
    
    /**
     * Redact Session
     *
     * Redact a Session, removing all identity data from Trinsic&#39;s servers.  Every application has a redaction period that dictates how long we will hold on to your users&#39; PII data. Once a session falls outside the redaction cutoff date, all PII will automatically be removed from that session.  You can utilize this endpoint to redact a session immediately.                Identity data that a user has chosen to save in their passkey-protected wallet will not be deleted.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void redactSessionTest() throws ApiException {
        String sessionId = null;
        
        api.redactSession(sessionId);
        
        // TODO: test validations
    }
    
}
