/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import id.trinsic.ApiClient;
/**
 * Exposed properties for the &#x60;a-be-id-login&#x60; Provider which do not directly map to the normalized IdentityData model.
 */
@JsonPropertyOrder({
  BelgiumIdCardProviderOutput.JSON_PROPERTY_FIRST_NAME,
  BelgiumIdCardProviderOutput.JSON_PROPERTY_LAST_NAME,
  BelgiumIdCardProviderOutput.JSON_PROPERTY_DATE_OF_BIRTH,
  BelgiumIdCardProviderOutput.JSON_PROPERTY_NATIONAL_REGISTER_NUMBER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-07T17:32:15.661174490Z[Etc/UTC]", comments = "Generator version: 7.21.0")
public class BelgiumIdCardProviderOutput {
  public static final String JSON_PROPERTY_FIRST_NAME = "firstName";
  @javax.annotation.Nonnull
  private String firstName;

  public static final String JSON_PROPERTY_LAST_NAME = "lastName";
  @javax.annotation.Nonnull
  private String lastName;

  public static final String JSON_PROPERTY_DATE_OF_BIRTH = "dateOfBirth";
  @javax.annotation.Nonnull
  private LocalDate dateOfBirth;

  public static final String JSON_PROPERTY_NATIONAL_REGISTER_NUMBER = "nationalRegisterNumber";
  @javax.annotation.Nonnull
  private String nationalRegisterNumber;

  public BelgiumIdCardProviderOutput() { 
  }

  public BelgiumIdCardProviderOutput firstName(@javax.annotation.Nonnull String firstName) {
    this.firstName = firstName;
    return this;
  }

  /**
   * The first name of the verified individual
   * @return firstName
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FIRST_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFirstName() {
    return firstName;
  }


  @JsonProperty(value = JSON_PROPERTY_FIRST_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFirstName(@javax.annotation.Nonnull String firstName) {
    this.firstName = firstName;
  }


  public BelgiumIdCardProviderOutput lastName(@javax.annotation.Nonnull String lastName) {
    this.lastName = lastName;
    return this;
  }

  /**
   * The last name of the verified individual
   * @return lastName
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LAST_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getLastName() {
    return lastName;
  }


  @JsonProperty(value = JSON_PROPERTY_LAST_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastName(@javax.annotation.Nonnull String lastName) {
    this.lastName = lastName;
  }


  public BelgiumIdCardProviderOutput dateOfBirth(@javax.annotation.Nonnull LocalDate dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
    return this;
  }

  /**
   * The date of birth of the verified individual
   * @return dateOfBirth
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DATE_OF_BIRTH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public LocalDate getDateOfBirth() {
    return dateOfBirth;
  }


  @JsonProperty(value = JSON_PROPERTY_DATE_OF_BIRTH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDateOfBirth(@javax.annotation.Nonnull LocalDate dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
  }


  public BelgiumIdCardProviderOutput nationalRegisterNumber(@javax.annotation.Nonnull String nationalRegisterNumber) {
    this.nationalRegisterNumber = nationalRegisterNumber;
    return this;
  }

  /**
   * The Belgian National Register Number (\&quot;Rijksregisternummer\&quot;) of the verified individual.              This is an 11-digit number in the format YYMMDDXXXCC, where: - YYMMDD represents the individual&#39;s date of birth (year, month, day). - XXX is a sequential birth number, odd for males and even for females. - CC is a checksum, calculated with the equation: 97 - (YYMMDDXXX mod 97)              For births in the year 2000 or later, the digit &#39;2&#39; is prepended to the first 9 digits during checksum calculation.
   * @return nationalRegisterNumber
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NATIONAL_REGISTER_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getNationalRegisterNumber() {
    return nationalRegisterNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_NATIONAL_REGISTER_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNationalRegisterNumber(@javax.annotation.Nonnull String nationalRegisterNumber) {
    this.nationalRegisterNumber = nationalRegisterNumber;
  }


  /**
   * Return true if this BelgiumIdCardProviderOutput object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BelgiumIdCardProviderOutput belgiumIdCardProviderOutput = (BelgiumIdCardProviderOutput) o;
    return Objects.equals(this.firstName, belgiumIdCardProviderOutput.firstName) &&
        Objects.equals(this.lastName, belgiumIdCardProviderOutput.lastName) &&
        Objects.equals(this.dateOfBirth, belgiumIdCardProviderOutput.dateOfBirth) &&
        Objects.equals(this.nationalRegisterNumber, belgiumIdCardProviderOutput.nationalRegisterNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstName, lastName, dateOfBirth, nationalRegisterNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BelgiumIdCardProviderOutput {\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    dateOfBirth: ").append(toIndentedString(dateOfBirth)).append("\n");
    sb.append("    nationalRegisterNumber: ").append(toIndentedString(nationalRegisterNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `firstName` to the URL query string
    if (getFirstName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfirstName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFirstName()))));
    }

    // add `lastName` to the URL query string
    if (getLastName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slastName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastName()))));
    }

    // add `dateOfBirth` to the URL query string
    if (getDateOfBirth() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdateOfBirth%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDateOfBirth()))));
    }

    // add `nationalRegisterNumber` to the URL query string
    if (getNationalRegisterNumber() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snationalRegisterNumber%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNationalRegisterNumber()))));
    }

    return joiner.toString();
  }
}

