/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import id.trinsic.ApiClient;
/**
 * FinalizeMdlExchangeRequest
 */
@JsonPropertyOrder({
  FinalizeMdlExchangeRequest.JSON_PROPERTY_VERIFICATION_PROFILE_ID,
  FinalizeMdlExchangeRequest.JSON_PROPERTY_EXCHANGE_ID,
  FinalizeMdlExchangeRequest.JSON_PROPERTY_EXCHANGE_CONTEXT,
  FinalizeMdlExchangeRequest.JSON_PROPERTY_RESPONSE_TOKEN
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-03T18:19:51.997950752Z[Etc/UTC]", comments = "Generator version: 7.13.0")
public class FinalizeMdlExchangeRequest {
  public static final String JSON_PROPERTY_VERIFICATION_PROFILE_ID = "verificationProfileId";
  @javax.annotation.Nonnull
  private UUID verificationProfileId;

  public static final String JSON_PROPERTY_EXCHANGE_ID = "exchangeId";
  @javax.annotation.Nonnull
  private UUID exchangeId;

  public static final String JSON_PROPERTY_EXCHANGE_CONTEXT = "exchangeContext";
  @javax.annotation.Nonnull
  private String exchangeContext;

  public static final String JSON_PROPERTY_RESPONSE_TOKEN = "responseToken";
  @javax.annotation.Nonnull
  private String responseToken;

  public FinalizeMdlExchangeRequest() { 
  }

  public FinalizeMdlExchangeRequest verificationProfileId(@javax.annotation.Nonnull UUID verificationProfileId) {
    this.verificationProfileId = verificationProfileId;
    return this;
  }

  /**
   * The ID of the VerificationProfile which was used to create the mDL exchange.
   * @return verificationProfileId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VERIFICATION_PROFILE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getVerificationProfileId() {
    return verificationProfileId;
  }


  @JsonProperty(JSON_PROPERTY_VERIFICATION_PROFILE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVerificationProfileId(@javax.annotation.Nonnull UUID verificationProfileId) {
    this.verificationProfileId = verificationProfileId;
  }


  public FinalizeMdlExchangeRequest exchangeId(@javax.annotation.Nonnull UUID exchangeId) {
    this.exchangeId = exchangeId;
    return this;
  }

  /**
   * The ID of the mDL exchange to finalize.
   * @return exchangeId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EXCHANGE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getExchangeId() {
    return exchangeId;
  }


  @JsonProperty(JSON_PROPERTY_EXCHANGE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExchangeId(@javax.annotation.Nonnull UUID exchangeId) {
    this.exchangeId = exchangeId;
  }


  public FinalizeMdlExchangeRequest exchangeContext(@javax.annotation.Nonnull String exchangeContext) {
    this.exchangeContext = exchangeContext;
    return this;
  }

  /**
   * The encrypted exchange context which was returned when the mDL exchange was created.
   * @return exchangeContext
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EXCHANGE_CONTEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getExchangeContext() {
    return exchangeContext;
  }


  @JsonProperty(JSON_PROPERTY_EXCHANGE_CONTEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExchangeContext(@javax.annotation.Nonnull String exchangeContext) {
    this.exchangeContext = exchangeContext;
  }


  public FinalizeMdlExchangeRequest responseToken(@javax.annotation.Nonnull String responseToken) {
    this.responseToken = responseToken;
    return this;
  }

  /**
   * The response token returned by Trinsic&#39;s SDK after a successful mDL exchange.
   * @return responseToken
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESPONSE_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getResponseToken() {
    return responseToken;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSE_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResponseToken(@javax.annotation.Nonnull String responseToken) {
    this.responseToken = responseToken;
  }


  /**
   * Return true if this FinalizeMdlExchangeRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FinalizeMdlExchangeRequest finalizeMdlExchangeRequest = (FinalizeMdlExchangeRequest) o;
    return Objects.equals(this.verificationProfileId, finalizeMdlExchangeRequest.verificationProfileId) &&
        Objects.equals(this.exchangeId, finalizeMdlExchangeRequest.exchangeId) &&
        Objects.equals(this.exchangeContext, finalizeMdlExchangeRequest.exchangeContext) &&
        Objects.equals(this.responseToken, finalizeMdlExchangeRequest.responseToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(verificationProfileId, exchangeId, exchangeContext, responseToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FinalizeMdlExchangeRequest {\n");
    sb.append("    verificationProfileId: ").append(toIndentedString(verificationProfileId)).append("\n");
    sb.append("    exchangeId: ").append(toIndentedString(exchangeId)).append("\n");
    sb.append("    exchangeContext: ").append(toIndentedString(exchangeContext)).append("\n");
    sb.append("    responseToken: ").append(toIndentedString(responseToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `verificationProfileId` to the URL query string
    if (getVerificationProfileId() != null) {
      joiner.add(String.format("%sverificationProfileId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVerificationProfileId()))));
    }

    // add `exchangeId` to the URL query string
    if (getExchangeId() != null) {
      joiner.add(String.format("%sexchangeId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExchangeId()))));
    }

    // add `exchangeContext` to the URL query string
    if (getExchangeContext() != null) {
      joiner.add(String.format("%sexchangeContext%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExchangeContext()))));
    }

    // add `responseToken` to the URL query string
    if (getResponseToken() != null) {
      joiner.add(String.format("%sresponseToken%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getResponseToken()))));
    }

    return joiner.toString();
  }
}

