/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import id.trinsic.ApiClient;
/**
 * Exposed properties for the &#x60;finnish-trust-network&#x60; Provider which do not directly map to the normalized IdentityData model.
 */
@JsonPropertyOrder({
  FinnishTrustNetworkProviderOutput.JSON_PROPERTY_FULL_NAME,
  FinnishTrustNetworkProviderOutput.JSON_PROPERTY_DATE_OF_BIRTH,
  FinnishTrustNetworkProviderOutput.JSON_PROPERTY_PERSONAL_IDENTIFICATION_CODE,
  FinnishTrustNetworkProviderOutput.JSON_PROPERTY_UNIQUE_IDENTIFICATION_NUMBER,
  FinnishTrustNetworkProviderOutput.JSON_PROPERTY_GIVEN_NAME,
  FinnishTrustNetworkProviderOutput.JSON_PROPERTY_FAMILY_NAME,
  FinnishTrustNetworkProviderOutput.JSON_PROPERTY_LEVEL_OF_ASSURANCE,
  FinnishTrustNetworkProviderOutput.JSON_PROPERTY_BANK,
  FinnishTrustNetworkProviderOutput.JSON_PROPERTY_PHONE_NUMBER,
  FinnishTrustNetworkProviderOutput.JSON_PROPERTY_ORGANIZATION_NAME,
  FinnishTrustNetworkProviderOutput.JSON_PROPERTY_VAT_NUMBER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-06T02:42:31.705521520Z[Etc/UTC]", comments = "Generator version: 7.21.0")
public class FinnishTrustNetworkProviderOutput {
  public static final String JSON_PROPERTY_FULL_NAME = "fullName";
  private JsonNullable<String> fullName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DATE_OF_BIRTH = "dateOfBirth";
  private JsonNullable<LocalDate> dateOfBirth = JsonNullable.<LocalDate>undefined();

  public static final String JSON_PROPERTY_PERSONAL_IDENTIFICATION_CODE = "personalIdentificationCode";
  private JsonNullable<String> personalIdentificationCode = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_UNIQUE_IDENTIFICATION_NUMBER = "uniqueIdentificationNumber";
  private JsonNullable<String> uniqueIdentificationNumber = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_GIVEN_NAME = "givenName";
  private JsonNullable<String> givenName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_FAMILY_NAME = "familyName";
  private JsonNullable<String> familyName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LEVEL_OF_ASSURANCE = "levelOfAssurance";
  private JsonNullable<String> levelOfAssurance = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_BANK = "bank";
  private JsonNullable<String> bank = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PHONE_NUMBER = "phoneNumber";
  private JsonNullable<String> phoneNumber = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ORGANIZATION_NAME = "organizationName";
  private JsonNullable<String> organizationName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_VAT_NUMBER = "vatNumber";
  private JsonNullable<String> vatNumber = JsonNullable.<String>undefined();

  public FinnishTrustNetworkProviderOutput() { 
  }

  public FinnishTrustNetworkProviderOutput fullName(@javax.annotation.Nullable String fullName) {
    this.fullName = JsonNullable.<String>of(fullName);
    return this;
  }

  /**
   * The full name of the individual.
   * @return fullName
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getFullName() {
        return fullName.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_FULL_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getFullName_JsonNullable() {
    return fullName;
  }
  
  @JsonProperty(JSON_PROPERTY_FULL_NAME)
  public void setFullName_JsonNullable(JsonNullable<String> fullName) {
    this.fullName = fullName;
  }

  public void setFullName(@javax.annotation.Nullable String fullName) {
    this.fullName = JsonNullable.<String>of(fullName);
  }


  public FinnishTrustNetworkProviderOutput dateOfBirth(@javax.annotation.Nullable LocalDate dateOfBirth) {
    this.dateOfBirth = JsonNullable.<LocalDate>of(dateOfBirth);
    return this;
  }

  /**
   * The date of birth of the individual.
   * @return dateOfBirth
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public LocalDate getDateOfBirth() {
        return dateOfBirth.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DATE_OF_BIRTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<LocalDate> getDateOfBirth_JsonNullable() {
    return dateOfBirth;
  }
  
  @JsonProperty(JSON_PROPERTY_DATE_OF_BIRTH)
  public void setDateOfBirth_JsonNullable(JsonNullable<LocalDate> dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
  }

  public void setDateOfBirth(@javax.annotation.Nullable LocalDate dateOfBirth) {
    this.dateOfBirth = JsonNullable.<LocalDate>of(dateOfBirth);
  }


  public FinnishTrustNetworkProviderOutput personalIdentificationCode(@javax.annotation.Nullable String personalIdentificationCode) {
    this.personalIdentificationCode = JsonNullable.<String>of(personalIdentificationCode);
    return this;
  }

  /**
   * The 11-digit Finnish Personal Identification Code (Henkilötunnus) of the verified individual.              This is in the format DDMMYYCZZZQ, where: - DDMMYY is the date of birth - C is a symbol which determines the century of birth - ZZZ is an individual number, indicating gender - Q is a checksum character              If ZZZ is even, the individual is female. If ZZZ is odd, the individual is male.              If C is &#39;+&#39;, the individual was born in the 19th century (1800-1899). If C is &#39;-&#39;, &#39;U&#39;, &#39;V&#39;, &#39;W&#39;, &#39;X&#39;, or &#39;Y&#39;, the individual was born in the 20th century (1900-1999). If C is &#39;A&#39;, &#39;B&#39;, &#39;C&#39;, &#39;D&#39;, &#39;E&#39;, or &#39;F&#39;, the individual was born in the 21st century (2000-2099).
   * @return personalIdentificationCode
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getPersonalIdentificationCode() {
        return personalIdentificationCode.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PERSONAL_IDENTIFICATION_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPersonalIdentificationCode_JsonNullable() {
    return personalIdentificationCode;
  }
  
  @JsonProperty(JSON_PROPERTY_PERSONAL_IDENTIFICATION_CODE)
  public void setPersonalIdentificationCode_JsonNullable(JsonNullable<String> personalIdentificationCode) {
    this.personalIdentificationCode = personalIdentificationCode;
  }

  public void setPersonalIdentificationCode(@javax.annotation.Nullable String personalIdentificationCode) {
    this.personalIdentificationCode = JsonNullable.<String>of(personalIdentificationCode);
  }


  public FinnishTrustNetworkProviderOutput uniqueIdentificationNumber(@javax.annotation.Nullable String uniqueIdentificationNumber) {
    this.uniqueIdentificationNumber = JsonNullable.<String>of(uniqueIdentificationNumber);
    return this;
  }

  /**
   * The 9-digit Finnish Unique Identification Number (FINUID, or sähköinen asiointitunnus SATU) of the verified individual. This number is typically used for online transactions and unlike the Finnish Personal Identification Code, does not reveal personal information such as birthdate.              The first 8 digits are randomly generated and the last character is a check control.
   * @return uniqueIdentificationNumber
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getUniqueIdentificationNumber() {
        return uniqueIdentificationNumber.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_UNIQUE_IDENTIFICATION_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getUniqueIdentificationNumber_JsonNullable() {
    return uniqueIdentificationNumber;
  }
  
  @JsonProperty(JSON_PROPERTY_UNIQUE_IDENTIFICATION_NUMBER)
  public void setUniqueIdentificationNumber_JsonNullable(JsonNullable<String> uniqueIdentificationNumber) {
    this.uniqueIdentificationNumber = uniqueIdentificationNumber;
  }

  public void setUniqueIdentificationNumber(@javax.annotation.Nullable String uniqueIdentificationNumber) {
    this.uniqueIdentificationNumber = JsonNullable.<String>of(uniqueIdentificationNumber);
  }


  public FinnishTrustNetworkProviderOutput givenName(@javax.annotation.Nullable String givenName) {
    this.givenName = JsonNullable.<String>of(givenName);
    return this;
  }

  /**
   * The given name of the individual.
   * @return givenName
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getGivenName() {
        return givenName.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_GIVEN_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getGivenName_JsonNullable() {
    return givenName;
  }
  
  @JsonProperty(JSON_PROPERTY_GIVEN_NAME)
  public void setGivenName_JsonNullable(JsonNullable<String> givenName) {
    this.givenName = givenName;
  }

  public void setGivenName(@javax.annotation.Nullable String givenName) {
    this.givenName = JsonNullable.<String>of(givenName);
  }


  public FinnishTrustNetworkProviderOutput familyName(@javax.annotation.Nullable String familyName) {
    this.familyName = JsonNullable.<String>of(familyName);
    return this;
  }

  /**
   * The family name of the individual.
   * @return familyName
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getFamilyName() {
        return familyName.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_FAMILY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getFamilyName_JsonNullable() {
    return familyName;
  }
  
  @JsonProperty(JSON_PROPERTY_FAMILY_NAME)
  public void setFamilyName_JsonNullable(JsonNullable<String> familyName) {
    this.familyName = familyName;
  }

  public void setFamilyName(@javax.annotation.Nullable String familyName) {
    this.familyName = JsonNullable.<String>of(familyName);
  }


  public FinnishTrustNetworkProviderOutput levelOfAssurance(@javax.annotation.Nullable String levelOfAssurance) {
    this.levelOfAssurance = JsonNullable.<String>of(levelOfAssurance);
    return this;
  }

  /**
   * The level of assurance (LOA) for the verification.              The LOA refers to the degree of confidence in the claimed identity of a person. The European Digital Identity Framework (EUDI) measures the confidence of the digital identity&#39;s verification and authentication strength by a set of requirements for different levels. To learn more, see: https://ec.europa.eu/digital-building-blocks/sites/spaces/DIGITAL/pages/467110081/eIDAS+Levels+of+Assurance              Possible values: - Low: The individual has self asserted their identity and multifactor authentication is not required. - Substantial: The individual has performed either a remote or in-person identity verification and multifactor authentication is required. - High: The individual has performed an in-person identity proofing with an authorized representative and has strong cryptographic authentication requirements such as using a smart card.
   * @return levelOfAssurance
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getLevelOfAssurance() {
        return levelOfAssurance.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LEVEL_OF_ASSURANCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLevelOfAssurance_JsonNullable() {
    return levelOfAssurance;
  }
  
  @JsonProperty(JSON_PROPERTY_LEVEL_OF_ASSURANCE)
  public void setLevelOfAssurance_JsonNullable(JsonNullable<String> levelOfAssurance) {
    this.levelOfAssurance = levelOfAssurance;
  }

  public void setLevelOfAssurance(@javax.annotation.Nullable String levelOfAssurance) {
    this.levelOfAssurance = JsonNullable.<String>of(levelOfAssurance);
  }


  public FinnishTrustNetworkProviderOutput bank(@javax.annotation.Nullable String bank) {
    this.bank = JsonNullable.<String>of(bank);
    return this;
  }

  /**
   * The bank used to perform the identification for the verified individual.
   * @return bank
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getBank() {
        return bank.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_BANK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getBank_JsonNullable() {
    return bank;
  }
  
  @JsonProperty(JSON_PROPERTY_BANK)
  public void setBank_JsonNullable(JsonNullable<String> bank) {
    this.bank = bank;
  }

  public void setBank(@javax.annotation.Nullable String bank) {
    this.bank = JsonNullable.<String>of(bank);
  }


  public FinnishTrustNetworkProviderOutput phoneNumber(@javax.annotation.Nullable String phoneNumber) {
    this.phoneNumber = JsonNullable.<String>of(phoneNumber);
    return this;
  }

  /**
   * The phone number of the verified individual.              This is only returned if the individual authenticated with MobileID (Mobiilivarmenne).
   * @return phoneNumber
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getPhoneNumber() {
        return phoneNumber.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PHONE_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPhoneNumber_JsonNullable() {
    return phoneNumber;
  }
  
  @JsonProperty(JSON_PROPERTY_PHONE_NUMBER)
  public void setPhoneNumber_JsonNullable(JsonNullable<String> phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public void setPhoneNumber(@javax.annotation.Nullable String phoneNumber) {
    this.phoneNumber = JsonNullable.<String>of(phoneNumber);
  }


  public FinnishTrustNetworkProviderOutput organizationName(@javax.annotation.Nullable String organizationName) {
    this.organizationName = JsonNullable.<String>of(organizationName);
    return this;
  }

  /**
   * The organization name that the individual is associated with.              This is returned for requests that contain the organization scope.
   * @return organizationName
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getOrganizationName() {
        return organizationName.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ORGANIZATION_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getOrganizationName_JsonNullable() {
    return organizationName;
  }
  
  @JsonProperty(JSON_PROPERTY_ORGANIZATION_NAME)
  public void setOrganizationName_JsonNullable(JsonNullable<String> organizationName) {
    this.organizationName = organizationName;
  }

  public void setOrganizationName(@javax.annotation.Nullable String organizationName) {
    this.organizationName = JsonNullable.<String>of(organizationName);
  }


  public FinnishTrustNetworkProviderOutput vatNumber(@javax.annotation.Nullable String vatNumber) {
    this.vatNumber = JsonNullable.<String>of(vatNumber);
    return this;
  }

  /**
   * The VAT number of the organization that the individual is associated with.              This is returned for requests that contain the organization scope.
   * @return vatNumber
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getVatNumber() {
        return vatNumber.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_VAT_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getVatNumber_JsonNullable() {
    return vatNumber;
  }
  
  @JsonProperty(JSON_PROPERTY_VAT_NUMBER)
  public void setVatNumber_JsonNullable(JsonNullable<String> vatNumber) {
    this.vatNumber = vatNumber;
  }

  public void setVatNumber(@javax.annotation.Nullable String vatNumber) {
    this.vatNumber = JsonNullable.<String>of(vatNumber);
  }


  /**
   * Return true if this FinnishTrustNetworkProviderOutput object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FinnishTrustNetworkProviderOutput finnishTrustNetworkProviderOutput = (FinnishTrustNetworkProviderOutput) o;
    return equalsNullable(this.fullName, finnishTrustNetworkProviderOutput.fullName) &&
        equalsNullable(this.dateOfBirth, finnishTrustNetworkProviderOutput.dateOfBirth) &&
        equalsNullable(this.personalIdentificationCode, finnishTrustNetworkProviderOutput.personalIdentificationCode) &&
        equalsNullable(this.uniqueIdentificationNumber, finnishTrustNetworkProviderOutput.uniqueIdentificationNumber) &&
        equalsNullable(this.givenName, finnishTrustNetworkProviderOutput.givenName) &&
        equalsNullable(this.familyName, finnishTrustNetworkProviderOutput.familyName) &&
        equalsNullable(this.levelOfAssurance, finnishTrustNetworkProviderOutput.levelOfAssurance) &&
        equalsNullable(this.bank, finnishTrustNetworkProviderOutput.bank) &&
        equalsNullable(this.phoneNumber, finnishTrustNetworkProviderOutput.phoneNumber) &&
        equalsNullable(this.organizationName, finnishTrustNetworkProviderOutput.organizationName) &&
        equalsNullable(this.vatNumber, finnishTrustNetworkProviderOutput.vatNumber);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(fullName), hashCodeNullable(dateOfBirth), hashCodeNullable(personalIdentificationCode), hashCodeNullable(uniqueIdentificationNumber), hashCodeNullable(givenName), hashCodeNullable(familyName), hashCodeNullable(levelOfAssurance), hashCodeNullable(bank), hashCodeNullable(phoneNumber), hashCodeNullable(organizationName), hashCodeNullable(vatNumber));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FinnishTrustNetworkProviderOutput {\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    dateOfBirth: ").append(toIndentedString(dateOfBirth)).append("\n");
    sb.append("    personalIdentificationCode: ").append(toIndentedString(personalIdentificationCode)).append("\n");
    sb.append("    uniqueIdentificationNumber: ").append(toIndentedString(uniqueIdentificationNumber)).append("\n");
    sb.append("    givenName: ").append(toIndentedString(givenName)).append("\n");
    sb.append("    familyName: ").append(toIndentedString(familyName)).append("\n");
    sb.append("    levelOfAssurance: ").append(toIndentedString(levelOfAssurance)).append("\n");
    sb.append("    bank: ").append(toIndentedString(bank)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    organizationName: ").append(toIndentedString(organizationName)).append("\n");
    sb.append("    vatNumber: ").append(toIndentedString(vatNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `fullName` to the URL query string
    if (getFullName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfullName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFullName()))));
    }

    // add `dateOfBirth` to the URL query string
    if (getDateOfBirth() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdateOfBirth%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDateOfBirth()))));
    }

    // add `personalIdentificationCode` to the URL query string
    if (getPersonalIdentificationCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spersonalIdentificationCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPersonalIdentificationCode()))));
    }

    // add `uniqueIdentificationNumber` to the URL query string
    if (getUniqueIdentificationNumber() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%suniqueIdentificationNumber%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUniqueIdentificationNumber()))));
    }

    // add `givenName` to the URL query string
    if (getGivenName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgivenName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGivenName()))));
    }

    // add `familyName` to the URL query string
    if (getFamilyName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfamilyName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFamilyName()))));
    }

    // add `levelOfAssurance` to the URL query string
    if (getLevelOfAssurance() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slevelOfAssurance%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLevelOfAssurance()))));
    }

    // add `bank` to the URL query string
    if (getBank() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbank%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBank()))));
    }

    // add `phoneNumber` to the URL query string
    if (getPhoneNumber() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sphoneNumber%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPhoneNumber()))));
    }

    // add `organizationName` to the URL query string
    if (getOrganizationName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sorganizationName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOrganizationName()))));
    }

    // add `vatNumber` to the URL query string
    if (getVatNumber() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svatNumber%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVatNumber()))));
    }

    return joiner.toString();
  }
}

