/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import id.trinsic.ApiClient;
/**
 * Given name information including the full given name and its structured components.
 */
@JsonPropertyOrder({
  FrenchNumeriqueGivenName.JSON_PROPERTY_FULL_GIVEN_NAME,
  FrenchNumeriqueGivenName.JSON_PROPERTY_FIRST_NAME,
  FrenchNumeriqueGivenName.JSON_PROPERTY_MIDDLE_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-12T16:16:44.206360395Z[Etc/UTC]", comments = "Generator version: 7.13.0")
public class FrenchNumeriqueGivenName {
  public static final String JSON_PROPERTY_FULL_GIVEN_NAME = "fullGivenName";
  private JsonNullable<String> fullGivenName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_FIRST_NAME = "firstName";
  private JsonNullable<String> firstName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_MIDDLE_NAME = "middleName";
  private JsonNullable<String> middleName = JsonNullable.<String>undefined();

  public FrenchNumeriqueGivenName() { 
  }

  public FrenchNumeriqueGivenName fullGivenName(@javax.annotation.Nullable String fullGivenName) {
    this.fullGivenName = JsonNullable.<String>of(fullGivenName);
    return this;
  }

  /**
   * Full given name(s) as recorded on the user&#39;s French identity document. If the user has multiple given names, they are separated by a single space.
   * @return fullGivenName
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getFullGivenName() {
        return fullGivenName.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FULL_GIVEN_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getFullGivenName_JsonNullable() {
    return fullGivenName;
  }
  
  @JsonProperty(JSON_PROPERTY_FULL_GIVEN_NAME)
  public void setFullGivenName_JsonNullable(JsonNullable<String> fullGivenName) {
    this.fullGivenName = fullGivenName;
  }

  public void setFullGivenName(@javax.annotation.Nullable String fullGivenName) {
    this.fullGivenName = JsonNullable.<String>of(fullGivenName);
  }


  public FrenchNumeriqueGivenName firstName(@javax.annotation.Nullable String firstName) {
    this.firstName = JsonNullable.<String>of(firstName);
    return this;
  }

  /**
   * First/primary given name (premier prénom).
   * @return firstName
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getFirstName() {
        return firstName.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getFirstName_JsonNullable() {
    return firstName;
  }
  
  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  public void setFirstName_JsonNullable(JsonNullable<String> firstName) {
    this.firstName = firstName;
  }

  public void setFirstName(@javax.annotation.Nullable String firstName) {
    this.firstName = JsonNullable.<String>of(firstName);
  }


  public FrenchNumeriqueGivenName middleName(@javax.annotation.Nullable String middleName) {
    this.middleName = JsonNullable.<String>of(middleName);
    return this;
  }

  /**
   * Middle name(s) (prénoms secondaires), separated by spaces if multiple.
   * @return middleName
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getMiddleName() {
        return middleName.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_MIDDLE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getMiddleName_JsonNullable() {
    return middleName;
  }
  
  @JsonProperty(JSON_PROPERTY_MIDDLE_NAME)
  public void setMiddleName_JsonNullable(JsonNullable<String> middleName) {
    this.middleName = middleName;
  }

  public void setMiddleName(@javax.annotation.Nullable String middleName) {
    this.middleName = JsonNullable.<String>of(middleName);
  }


  /**
   * Return true if this FrenchNumeriqueGivenName object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FrenchNumeriqueGivenName frenchNumeriqueGivenName = (FrenchNumeriqueGivenName) o;
    return equalsNullable(this.fullGivenName, frenchNumeriqueGivenName.fullGivenName) &&
        equalsNullable(this.firstName, frenchNumeriqueGivenName.firstName) &&
        equalsNullable(this.middleName, frenchNumeriqueGivenName.middleName);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(fullGivenName), hashCodeNullable(firstName), hashCodeNullable(middleName));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FrenchNumeriqueGivenName {\n");
    sb.append("    fullGivenName: ").append(toIndentedString(fullGivenName)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    middleName: ").append(toIndentedString(middleName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `fullGivenName` to the URL query string
    if (getFullGivenName() != null) {
      joiner.add(String.format("%sfullGivenName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFullGivenName()))));
    }

    // add `firstName` to the URL query string
    if (getFirstName() != null) {
      joiner.add(String.format("%sfirstName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFirstName()))));
    }

    // add `middleName` to the URL query string
    if (getMiddleName() != null) {
      joiner.add(String.format("%smiddleName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMiddleName()))));
    }

    return joiner.toString();
  }
}

