/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.trinsic.api.models.MdlExchangeMechanism;
import id.trinsic.api.models.Raw18013RequestInput;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import id.trinsic.ApiClient;
/**
 * GoogleWalletInput
 */
@JsonPropertyOrder({
  GoogleWalletInput.JSON_PROPERTY_EXCHANGE_MECHANISM,
  GoogleWalletInput.JSON_PROPERTY_PREVIEW_RAW18013_REQUEST
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-06T02:42:31.705521520Z[Etc/UTC]", comments = "Generator version: 7.21.0")
public class GoogleWalletInput {
  public static final String JSON_PROPERTY_EXCHANGE_MECHANISM = "exchangeMechanism";
  private JsonNullable<MdlExchangeMechanism> exchangeMechanism = JsonNullable.<MdlExchangeMechanism>undefined();

  public static final String JSON_PROPERTY_PREVIEW_RAW18013_REQUEST = "preview_raw18013Request";
  private JsonNullable<Raw18013RequestInput> previewRaw18013Request = JsonNullable.<Raw18013RequestInput>undefined();

  public GoogleWalletInput() { 
  }

  public GoogleWalletInput exchangeMechanism(@javax.annotation.Nullable MdlExchangeMechanism exchangeMechanism) {
    this.exchangeMechanism = JsonNullable.<MdlExchangeMechanism>of(exchangeMechanism);
    return this;
  }

  /**
   * The exchange mechanism to use for this Google Wallet verification.              Use &#x60;DigitalCredentialsApi&#x60; for Digital Credentials API on web, or &#x60;NativeApp&#x60; for a native Android app.
   * @return exchangeMechanism
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public MdlExchangeMechanism getExchangeMechanism() {
        return exchangeMechanism.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_EXCHANGE_MECHANISM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<MdlExchangeMechanism> getExchangeMechanism_JsonNullable() {
    return exchangeMechanism;
  }
  
  @JsonProperty(JSON_PROPERTY_EXCHANGE_MECHANISM)
  public void setExchangeMechanism_JsonNullable(JsonNullable<MdlExchangeMechanism> exchangeMechanism) {
    this.exchangeMechanism = exchangeMechanism;
  }

  public void setExchangeMechanism(@javax.annotation.Nullable MdlExchangeMechanism exchangeMechanism) {
    this.exchangeMechanism = JsonNullable.<MdlExchangeMechanism>of(exchangeMechanism);
  }


  public GoogleWalletInput previewRaw18013Request(@javax.annotation.Nullable Raw18013RequestInput previewRaw18013Request) {
    this.previewRaw18013Request = JsonNullable.<Raw18013RequestInput>of(previewRaw18013Request);
    return this;
  }

  /**
   * **Preview feature: not suitable for production use cases**              The raw 18013-7 exchange request to use for this verification.              If set, this overrides any default configuration on your Verification Profile.              NOTE: This parameter has no effect in live mode for Google Wallet verifications. Dynamic requests are currently only supported in test mode for Google Wallet.
   * @return previewRaw18013Request
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Raw18013RequestInput getPreviewRaw18013Request() {
        return previewRaw18013Request.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PREVIEW_RAW18013_REQUEST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Raw18013RequestInput> getPreviewRaw18013Request_JsonNullable() {
    return previewRaw18013Request;
  }
  
  @JsonProperty(JSON_PROPERTY_PREVIEW_RAW18013_REQUEST)
  public void setPreviewRaw18013Request_JsonNullable(JsonNullable<Raw18013RequestInput> previewRaw18013Request) {
    this.previewRaw18013Request = previewRaw18013Request;
  }

  public void setPreviewRaw18013Request(@javax.annotation.Nullable Raw18013RequestInput previewRaw18013Request) {
    this.previewRaw18013Request = JsonNullable.<Raw18013RequestInput>of(previewRaw18013Request);
  }


  /**
   * Return true if this GoogleWalletInput object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GoogleWalletInput googleWalletInput = (GoogleWalletInput) o;
    return equalsNullable(this.exchangeMechanism, googleWalletInput.exchangeMechanism) &&
        equalsNullable(this.previewRaw18013Request, googleWalletInput.previewRaw18013Request);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(exchangeMechanism), hashCodeNullable(previewRaw18013Request));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GoogleWalletInput {\n");
    sb.append("    exchangeMechanism: ").append(toIndentedString(exchangeMechanism)).append("\n");
    sb.append("    previewRaw18013Request: ").append(toIndentedString(previewRaw18013Request)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `exchangeMechanism` to the URL query string
    if (getExchangeMechanism() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexchangeMechanism%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExchangeMechanism()))));
    }

    // add `preview_raw18013Request` to the URL query string
    if (getPreviewRaw18013Request() != null) {
      joiner.add(getPreviewRaw18013Request().toUrlQueryString(prefix + "preview_raw18013Request" + suffix));
    }

    return joiner.toString();
  }
}

