/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import id.trinsic.ApiClient;
/**
 * Exposed properties for the &#x60;guatemala-cui-lookup&#x60; Provider which do not directly map to the normalized IdentityData model.
 */
@JsonPropertyOrder({
  GuatemalaCuiProviderOutput.JSON_PROPERTY_FULL_NAME,
  GuatemalaCuiProviderOutput.JSON_PROPERTY_GIVEN_NAME,
  GuatemalaCuiProviderOutput.JSON_PROPERTY_FAMILY_NAME,
  GuatemalaCuiProviderOutput.JSON_PROPERTY_DATE_OF_BIRTH,
  GuatemalaCuiProviderOutput.JSON_PROPERTY_DOCUMENT_NUMBER,
  GuatemalaCuiProviderOutput.JSON_PROPERTY_SERIAL_DIGITS,
  GuatemalaCuiProviderOutput.JSON_PROPERTY_VERIFIER_DIGIT,
  GuatemalaCuiProviderOutput.JSON_PROPERTY_GEOGRAPHIC_DIGITS,
  GuatemalaCuiProviderOutput.JSON_PROPERTY_SEX,
  GuatemalaCuiProviderOutput.JSON_PROPERTY_ARRAY_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-06T02:42:31.705521520Z[Etc/UTC]", comments = "Generator version: 7.21.0")
public class GuatemalaCuiProviderOutput {
  public static final String JSON_PROPERTY_FULL_NAME = "fullName";
  @javax.annotation.Nonnull
  private String fullName;

  public static final String JSON_PROPERTY_GIVEN_NAME = "givenName";
  @javax.annotation.Nonnull
  private String givenName;

  public static final String JSON_PROPERTY_FAMILY_NAME = "familyName";
  @javax.annotation.Nonnull
  private String familyName;

  public static final String JSON_PROPERTY_DATE_OF_BIRTH = "dateOfBirth";
  private JsonNullable<LocalDate> dateOfBirth = JsonNullable.<LocalDate>undefined();

  public static final String JSON_PROPERTY_DOCUMENT_NUMBER = "documentNumber";
  @javax.annotation.Nonnull
  private String documentNumber;

  public static final String JSON_PROPERTY_SERIAL_DIGITS = "serialDigits";
  @javax.annotation.Nonnull
  private String serialDigits;

  public static final String JSON_PROPERTY_VERIFIER_DIGIT = "verifierDigit";
  @javax.annotation.Nonnull
  private String verifierDigit;

  public static final String JSON_PROPERTY_GEOGRAPHIC_DIGITS = "geographicDigits";
  @javax.annotation.Nonnull
  private String geographicDigits;

  public static final String JSON_PROPERTY_SEX = "sex";
  @javax.annotation.Nonnull
  private String sex;

  public static final String JSON_PROPERTY_ARRAY_NAME = "arrayName";
  @javax.annotation.Nonnull
  private List<String> arrayName = new ArrayList<>();

  public GuatemalaCuiProviderOutput() { 
  }

  public GuatemalaCuiProviderOutput fullName(@javax.annotation.Nonnull String fullName) {
    this.fullName = fullName;
    return this;
  }

  /**
   * Full name, including given and family names of the CUI holder.
   * @return fullName
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FULL_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFullName() {
    return fullName;
  }


  @JsonProperty(value = JSON_PROPERTY_FULL_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFullName(@javax.annotation.Nonnull String fullName) {
    this.fullName = fullName;
  }


  public GuatemalaCuiProviderOutput givenName(@javax.annotation.Nonnull String givenName) {
    this.givenName = givenName;
    return this;
  }

  /**
   * Given name(s) of the CUI holder.
   * @return givenName
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_GIVEN_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getGivenName() {
    return givenName;
  }


  @JsonProperty(value = JSON_PROPERTY_GIVEN_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGivenName(@javax.annotation.Nonnull String givenName) {
    this.givenName = givenName;
  }


  public GuatemalaCuiProviderOutput familyName(@javax.annotation.Nonnull String familyName) {
    this.familyName = familyName;
    return this;
  }

  /**
   * Family name(s) of the CUI holder, including maternal and paternal names.
   * @return familyName
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FAMILY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFamilyName() {
    return familyName;
  }


  @JsonProperty(value = JSON_PROPERTY_FAMILY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFamilyName(@javax.annotation.Nonnull String familyName) {
    this.familyName = familyName;
  }


  public GuatemalaCuiProviderOutput dateOfBirth(@javax.annotation.Nullable LocalDate dateOfBirth) {
    this.dateOfBirth = JsonNullable.<LocalDate>of(dateOfBirth);
    return this;
  }

  /**
   * Date of birth of the CUI holder.
   * @return dateOfBirth
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public LocalDate getDateOfBirth() {
        return dateOfBirth.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DATE_OF_BIRTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<LocalDate> getDateOfBirth_JsonNullable() {
    return dateOfBirth;
  }
  
  @JsonProperty(JSON_PROPERTY_DATE_OF_BIRTH)
  public void setDateOfBirth_JsonNullable(JsonNullable<LocalDate> dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
  }

  public void setDateOfBirth(@javax.annotation.Nullable LocalDate dateOfBirth) {
    this.dateOfBirth = JsonNullable.<LocalDate>of(dateOfBirth);
  }


  public GuatemalaCuiProviderOutput documentNumber(@javax.annotation.Nonnull String documentNumber) {
    this.documentNumber = documentNumber;
    return this;
  }

  /**
   * The Guatemalan Código Único de Identificación (CUI) number.              Assigned and maintained by RENAP (Registro Nacional de las Personas). Official format: exactly 13 numeric digits. 8 RENAP-assigned serial digits, 1 verifier digit (dígito verificador), and 4 geographic digits for department and municipality of birth. The CUI is printed on the Documento Personal de Identificación (DPI) in three groups (4–5–4) separated by spaces.              Trinsic normalizes to digits-only when returning the result, automatically removing spaces, dots, hyphens, and other non-alphanumeric characters.              No verifier algorithm appears in publicly accessible RENAP resources. Community-maintained validators often use modulus-11 (non-official).
   * @return documentNumber
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DOCUMENT_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDocumentNumber() {
    return documentNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_DOCUMENT_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDocumentNumber(@javax.annotation.Nonnull String documentNumber) {
    this.documentNumber = documentNumber;
  }


  public GuatemalaCuiProviderOutput serialDigits(@javax.annotation.Nonnull String serialDigits) {
    this.serialDigits = serialDigits;
    return this;
  }

  /**
   * The first 8 digits of the CUI: the portion RENAP assigns from its registration system, before the verifier digit and the four-place geographic codes. Called the “serial” numbers in community-maintained validators.
   * @return serialDigits
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SERIAL_DIGITS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSerialDigits() {
    return serialDigits;
  }


  @JsonProperty(value = JSON_PROPERTY_SERIAL_DIGITS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSerialDigits(@javax.annotation.Nonnull String serialDigits) {
    this.serialDigits = serialDigits;
  }


  public GuatemalaCuiProviderOutput verifierDigit(@javax.annotation.Nonnull String verifierDigit) {
    this.verifierDigit = verifierDigit;
    return this;
  }

  /**
   * The 9th digit of the CUI (verifier digit / dígito verificador). No verifier algorithm appears in publicly accessible RENAP resources.              However, community-maintained validators often use modulus-11 (non-official).
   * @return verifierDigit
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_VERIFIER_DIGIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getVerifierDigit() {
    return verifierDigit;
  }


  @JsonProperty(value = JSON_PROPERTY_VERIFIER_DIGIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVerifierDigit(@javax.annotation.Nonnull String verifierDigit) {
    this.verifierDigit = verifierDigit;
  }


  public GuatemalaCuiProviderOutput geographicDigits(@javax.annotation.Nonnull String geographicDigits) {
    this.geographicDigits = geographicDigits;
    return this;
  }

  /**
   * The last four digits encode birthplace department and municipality. There is not a publicly accessible dataset from RENAP for geographic codes. The INE (Instituto Nacional de Estadística y Censos) provides a dictionary of variables (Educación Formal 2024) that includes statistical codes for decoding departments and municipalities. Be careful using these resources, as these codes are not official RENAP codes. They may not always map to the correct department and municipality for consular registrations, naturalizations, foreign residents, and other edge cases.              For the dataset, see: https://datos.ine.gob.gt/dataset/educacion-formal-2024 under \&quot;Diccionario de Variables (Educación Formal 2024)\&quot;
   * @return geographicDigits
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_GEOGRAPHIC_DIGITS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getGeographicDigits() {
    return geographicDigits;
  }


  @JsonProperty(value = JSON_PROPERTY_GEOGRAPHIC_DIGITS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGeographicDigits(@javax.annotation.Nonnull String geographicDigits) {
    this.geographicDigits = geographicDigits;
  }


  public GuatemalaCuiProviderOutput sex(@javax.annotation.Nonnull String sex) {
    this.sex = sex;
    return this;
  }

  /**
   * Sex of the CUI holder.              Possible values: - Male - Female - Unknown
   * @return sex
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SEX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSex() {
    return sex;
  }


  @JsonProperty(value = JSON_PROPERTY_SEX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSex(@javax.annotation.Nonnull String sex) {
    this.sex = sex;
  }


  public GuatemalaCuiProviderOutput arrayName(@javax.annotation.Nonnull List<String> arrayName) {
    this.arrayName = arrayName;
    return this;
  }

  public GuatemalaCuiProviderOutput addArrayNameItem(String arrayNameItem) {
    if (this.arrayName == null) {
      this.arrayName = new ArrayList<>();
    }
    this.arrayName.add(arrayNameItem);
    return this;
  }

  /**
   * All names of the CUI holder, as an array of strings (e.g. given and family name parts).
   * @return arrayName
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ARRAY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getArrayName() {
    return arrayName;
  }


  @JsonProperty(value = JSON_PROPERTY_ARRAY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setArrayName(@javax.annotation.Nonnull List<String> arrayName) {
    this.arrayName = arrayName;
  }


  /**
   * Return true if this GuatemalaCuiProviderOutput object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GuatemalaCuiProviderOutput guatemalaCuiProviderOutput = (GuatemalaCuiProviderOutput) o;
    return Objects.equals(this.fullName, guatemalaCuiProviderOutput.fullName) &&
        Objects.equals(this.givenName, guatemalaCuiProviderOutput.givenName) &&
        Objects.equals(this.familyName, guatemalaCuiProviderOutput.familyName) &&
        equalsNullable(this.dateOfBirth, guatemalaCuiProviderOutput.dateOfBirth) &&
        Objects.equals(this.documentNumber, guatemalaCuiProviderOutput.documentNumber) &&
        Objects.equals(this.serialDigits, guatemalaCuiProviderOutput.serialDigits) &&
        Objects.equals(this.verifierDigit, guatemalaCuiProviderOutput.verifierDigit) &&
        Objects.equals(this.geographicDigits, guatemalaCuiProviderOutput.geographicDigits) &&
        Objects.equals(this.sex, guatemalaCuiProviderOutput.sex) &&
        Objects.equals(this.arrayName, guatemalaCuiProviderOutput.arrayName);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(fullName, givenName, familyName, hashCodeNullable(dateOfBirth), documentNumber, serialDigits, verifierDigit, geographicDigits, sex, arrayName);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GuatemalaCuiProviderOutput {\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    givenName: ").append(toIndentedString(givenName)).append("\n");
    sb.append("    familyName: ").append(toIndentedString(familyName)).append("\n");
    sb.append("    dateOfBirth: ").append(toIndentedString(dateOfBirth)).append("\n");
    sb.append("    documentNumber: ").append(toIndentedString(documentNumber)).append("\n");
    sb.append("    serialDigits: ").append(toIndentedString(serialDigits)).append("\n");
    sb.append("    verifierDigit: ").append(toIndentedString(verifierDigit)).append("\n");
    sb.append("    geographicDigits: ").append(toIndentedString(geographicDigits)).append("\n");
    sb.append("    sex: ").append(toIndentedString(sex)).append("\n");
    sb.append("    arrayName: ").append(toIndentedString(arrayName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `fullName` to the URL query string
    if (getFullName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfullName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFullName()))));
    }

    // add `givenName` to the URL query string
    if (getGivenName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgivenName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGivenName()))));
    }

    // add `familyName` to the URL query string
    if (getFamilyName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfamilyName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFamilyName()))));
    }

    // add `dateOfBirth` to the URL query string
    if (getDateOfBirth() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdateOfBirth%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDateOfBirth()))));
    }

    // add `documentNumber` to the URL query string
    if (getDocumentNumber() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdocumentNumber%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDocumentNumber()))));
    }

    // add `serialDigits` to the URL query string
    if (getSerialDigits() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sserialDigits%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSerialDigits()))));
    }

    // add `verifierDigit` to the URL query string
    if (getVerifierDigit() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sverifierDigit%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVerifierDigit()))));
    }

    // add `geographicDigits` to the URL query string
    if (getGeographicDigits() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgeographicDigits%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGeographicDigits()))));
    }

    // add `sex` to the URL query string
    if (getSex() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssex%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSex()))));
    }

    // add `arrayName` to the URL query string
    if (getArrayName() != null) {
      for (int i = 0; i < getArrayName().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sarrayName%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getArrayName().get(i)))));
      }
    }

    return joiner.toString();
  }
}

