/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import id.trinsic.ApiClient;
/**
 * Exposed properties for the &#x60;a-lv-eparaksts-mobile-login&#x60; Provider which do not directly map to the normalized IdentityData model.
 */
@JsonPropertyOrder({
  LatviaEparakstsMobileProviderOutput.JSON_PROPERTY_FIRST_NAME,
  LatviaEparakstsMobileProviderOutput.JSON_PROPERTY_LAST_NAME,
  LatviaEparakstsMobileProviderOutput.JSON_PROPERTY_PERSONAL_CODE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-06T02:42:31.705521520Z[Etc/UTC]", comments = "Generator version: 7.21.0")
public class LatviaEparakstsMobileProviderOutput {
  public static final String JSON_PROPERTY_FIRST_NAME = "firstName";
  @javax.annotation.Nonnull
  private String firstName;

  public static final String JSON_PROPERTY_LAST_NAME = "lastName";
  @javax.annotation.Nonnull
  private String lastName;

  public static final String JSON_PROPERTY_PERSONAL_CODE = "personalCode";
  @javax.annotation.Nonnull
  private String personalCode;

  public LatviaEparakstsMobileProviderOutput() { 
  }

  public LatviaEparakstsMobileProviderOutput firstName(@javax.annotation.Nonnull String firstName) {
    this.firstName = firstName;
    return this;
  }

  /**
   * The first name of the verified individual
   * @return firstName
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FIRST_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFirstName() {
    return firstName;
  }


  @JsonProperty(value = JSON_PROPERTY_FIRST_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFirstName(@javax.annotation.Nonnull String firstName) {
    this.firstName = firstName;
  }


  public LatviaEparakstsMobileProviderOutput lastName(@javax.annotation.Nonnull String lastName) {
    this.lastName = lastName;
    return this;
  }

  /**
   * The last name of the verified individual
   * @return lastName
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LAST_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getLastName() {
    return lastName;
  }


  @JsonProperty(value = JSON_PROPERTY_LAST_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastName(@javax.annotation.Nonnull String lastName) {
    this.lastName = lastName;
  }


  public LatviaEparakstsMobileProviderOutput personalCode(@javax.annotation.Nonnull String personalCode) {
    this.personalCode = personalCode;
    return this;
  }

  /**
   * The 11-digit Latvian personal code (\&quot;personas kods\&quot;) of the verified individual.              This has two possible formats, depending on whether the personal code was issued after July 1, 2017.              For personal codes issued before July 1, 2017, the format is DDMMYY-CZZZQ, where: - DDMMYY is the date of birth, followed by an optional hyphen - C represents the century of birth (&#39;0&#39; for 1800-1899, &#39;1&#39; for 1900-1999, &#39;2&#39; for 2000-2099) - ZZZ is a serial number - Q is a checksum digit              For personal codes issued on or after July 1, 2017, the format is 32ZZZZZZZZQ, where: - 32 is a fixed prefix - ZZZZZZZQ are 8 random digits - Q is a checksum digit              NOTE: Individuals born before July 1, 2017 can elect to be issued a new personal code which does not contain their birthdate. Therefore, no concrete assumptions may be made about an individual&#39;s date of birth based solely on the format of their personal code.
   * @return personalCode
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PERSONAL_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPersonalCode() {
    return personalCode;
  }


  @JsonProperty(value = JSON_PROPERTY_PERSONAL_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPersonalCode(@javax.annotation.Nonnull String personalCode) {
    this.personalCode = personalCode;
  }


  /**
   * Return true if this LatviaEparakstsMobileProviderOutput object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LatviaEparakstsMobileProviderOutput latviaEparakstsMobileProviderOutput = (LatviaEparakstsMobileProviderOutput) o;
    return Objects.equals(this.firstName, latviaEparakstsMobileProviderOutput.firstName) &&
        Objects.equals(this.lastName, latviaEparakstsMobileProviderOutput.lastName) &&
        Objects.equals(this.personalCode, latviaEparakstsMobileProviderOutput.personalCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstName, lastName, personalCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LatviaEparakstsMobileProviderOutput {\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    personalCode: ").append(toIndentedString(personalCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `firstName` to the URL query string
    if (getFirstName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfirstName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFirstName()))));
    }

    // add `lastName` to the URL query string
    if (getLastName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slastName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastName()))));
    }

    // add `personalCode` to the URL query string
    if (getPersonalCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spersonalCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPersonalCode()))));
    }

    return joiner.toString();
  }
}

