/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import id.trinsic.ApiClient;
/**
 * PolandMobywatelMatchInput
 */
@JsonPropertyOrder({
  PolandMobywatelMatchInput.JSON_PROPERTY_GIVEN_NAME,
  PolandMobywatelMatchInput.JSON_PROPERTY_FAMILY_NAME,
  PolandMobywatelMatchInput.JSON_PROPERTY_DATE_OF_BIRTH,
  PolandMobywatelMatchInput.JSON_PROPERTY_NATIONALITY,
  PolandMobywatelMatchInput.JSON_PROPERTY_PERSONAL_NUMBER,
  PolandMobywatelMatchInput.JSON_PROPERTY_EXPIRATION_DATE,
  PolandMobywatelMatchInput.JSON_PROPERTY_SELFIE_BYTES,
  PolandMobywatelMatchInput.JSON_PROPERTY_SELFIE_IMAGE_MIME_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-06T02:42:31.705521520Z[Etc/UTC]", comments = "Generator version: 7.21.0")
public class PolandMobywatelMatchInput {
  public static final String JSON_PROPERTY_GIVEN_NAME = "givenName";
  private JsonNullable<String> givenName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_FAMILY_NAME = "familyName";
  private JsonNullable<String> familyName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DATE_OF_BIRTH = "dateOfBirth";
  private JsonNullable<String> dateOfBirth = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_NATIONALITY = "nationality";
  private JsonNullable<String> nationality = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PERSONAL_NUMBER = "personalNumber";
  private JsonNullable<String> personalNumber = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_EXPIRATION_DATE = "expirationDate";
  private JsonNullable<String> expirationDate = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SELFIE_BYTES = "selfieBytes";
  private JsonNullable<byte[]> selfieBytes = JsonNullable.<byte[]>undefined();

  public static final String JSON_PROPERTY_SELFIE_IMAGE_MIME_TYPE = "selfieImageMimeType";
  private JsonNullable<String> selfieImageMimeType = JsonNullable.<String>undefined();

  public PolandMobywatelMatchInput() { 
  }

  public PolandMobywatelMatchInput givenName(@javax.annotation.Nullable String givenName) {
    this.givenName = JsonNullable.<String>of(givenName);
    return this;
  }

  /**
   * Given name as it appears on mobile ID (mDowód).
   * @return givenName
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getGivenName() {
        return givenName.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_GIVEN_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getGivenName_JsonNullable() {
    return givenName;
  }
  
  @JsonProperty(JSON_PROPERTY_GIVEN_NAME)
  public void setGivenName_JsonNullable(JsonNullable<String> givenName) {
    this.givenName = givenName;
  }

  public void setGivenName(@javax.annotation.Nullable String givenName) {
    this.givenName = JsonNullable.<String>of(givenName);
  }


  public PolandMobywatelMatchInput familyName(@javax.annotation.Nullable String familyName) {
    this.familyName = JsonNullable.<String>of(familyName);
    return this;
  }

  /**
   * Current legal family name (nazwisko) as it appears on mobile ID (mDowód).              In Poland the current legal family name (nazwisko) is a separate idea from your birth family name (nazwisko rodowe). They often match, but they can differ after marriage, adoption, or a court-ordered change.
   * @return familyName
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getFamilyName() {
        return familyName.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_FAMILY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getFamilyName_JsonNullable() {
    return familyName;
  }
  
  @JsonProperty(JSON_PROPERTY_FAMILY_NAME)
  public void setFamilyName_JsonNullable(JsonNullable<String> familyName) {
    this.familyName = familyName;
  }

  public void setFamilyName(@javax.annotation.Nullable String familyName) {
    this.familyName = JsonNullable.<String>of(familyName);
  }


  public PolandMobywatelMatchInput dateOfBirth(@javax.annotation.Nullable String dateOfBirth) {
    this.dateOfBirth = JsonNullable.<String>of(dateOfBirth);
    return this;
  }

  /**
   * Date of birth as it appears on mobile ID (mDowód).
   * @return dateOfBirth
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getDateOfBirth() {
        return dateOfBirth.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DATE_OF_BIRTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDateOfBirth_JsonNullable() {
    return dateOfBirth;
  }
  
  @JsonProperty(JSON_PROPERTY_DATE_OF_BIRTH)
  public void setDateOfBirth_JsonNullable(JsonNullable<String> dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
  }

  public void setDateOfBirth(@javax.annotation.Nullable String dateOfBirth) {
    this.dateOfBirth = JsonNullable.<String>of(dateOfBirth);
  }


  public PolandMobywatelMatchInput nationality(@javax.annotation.Nullable String nationality) {
    this.nationality = JsonNullable.<String>of(nationality);
    return this;
  }

  /**
   * Nationality as it appears on mobile ID (mDowód).
   * @return nationality
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getNationality() {
        return nationality.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_NATIONALITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getNationality_JsonNullable() {
    return nationality;
  }
  
  @JsonProperty(JSON_PROPERTY_NATIONALITY)
  public void setNationality_JsonNullable(JsonNullable<String> nationality) {
    this.nationality = nationality;
  }

  public void setNationality(@javax.annotation.Nullable String nationality) {
    this.nationality = JsonNullable.<String>of(nationality);
  }


  public PolandMobywatelMatchInput personalNumber(@javax.annotation.Nullable String personalNumber) {
    this.personalNumber = JsonNullable.<String>of(personalNumber);
    return this;
  }

  /**
   * Polish national identification number (PESEL) as it appears on mobile ID (mDowód).              NOTE: The provided example value is a randomly generated, but valid PESEL number that does not correspond to a real person.
   * @return personalNumber
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getPersonalNumber() {
        return personalNumber.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PERSONAL_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPersonalNumber_JsonNullable() {
    return personalNumber;
  }
  
  @JsonProperty(JSON_PROPERTY_PERSONAL_NUMBER)
  public void setPersonalNumber_JsonNullable(JsonNullable<String> personalNumber) {
    this.personalNumber = personalNumber;
  }

  public void setPersonalNumber(@javax.annotation.Nullable String personalNumber) {
    this.personalNumber = JsonNullable.<String>of(personalNumber);
  }


  public PolandMobywatelMatchInput expirationDate(@javax.annotation.Nullable String expirationDate) {
    this.expirationDate = JsonNullable.<String>of(expirationDate);
    return this;
  }

  /**
   * Document expiration date as it appears on mobile ID (mDowód).
   * @return expirationDate
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getExpirationDate() {
        return expirationDate.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_EXPIRATION_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getExpirationDate_JsonNullable() {
    return expirationDate;
  }
  
  @JsonProperty(JSON_PROPERTY_EXPIRATION_DATE)
  public void setExpirationDate_JsonNullable(JsonNullable<String> expirationDate) {
    this.expirationDate = expirationDate;
  }

  public void setExpirationDate(@javax.annotation.Nullable String expirationDate) {
    this.expirationDate = JsonNullable.<String>of(expirationDate);
  }


  public PolandMobywatelMatchInput selfieBytes(@javax.annotation.Nullable byte[] selfieBytes) {
    this.selfieBytes = JsonNullable.<byte[]>of(selfieBytes);
    return this;
  }

  /**
   * The raw bytes of the selfie image collected from the user.
   * @return selfieBytes
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public byte[] getSelfieBytes() {
        return selfieBytes.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SELFIE_BYTES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<byte[]> getSelfieBytes_JsonNullable() {
    return selfieBytes;
  }
  
  @JsonProperty(JSON_PROPERTY_SELFIE_BYTES)
  public void setSelfieBytes_JsonNullable(JsonNullable<byte[]> selfieBytes) {
    this.selfieBytes = selfieBytes;
  }

  public void setSelfieBytes(@javax.annotation.Nullable byte[] selfieBytes) {
    this.selfieBytes = JsonNullable.<byte[]>of(selfieBytes);
  }


  public PolandMobywatelMatchInput selfieImageMimeType(@javax.annotation.Nullable String selfieImageMimeType) {
    this.selfieImageMimeType = JsonNullable.<String>of(selfieImageMimeType);
    return this;
  }

  /**
   * The MIME Type of the file contained in SelfieBytes.              Only JPEG or PNG formats are supported.
   * @return selfieImageMimeType
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getSelfieImageMimeType() {
        return selfieImageMimeType.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SELFIE_IMAGE_MIME_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSelfieImageMimeType_JsonNullable() {
    return selfieImageMimeType;
  }
  
  @JsonProperty(JSON_PROPERTY_SELFIE_IMAGE_MIME_TYPE)
  public void setSelfieImageMimeType_JsonNullable(JsonNullable<String> selfieImageMimeType) {
    this.selfieImageMimeType = selfieImageMimeType;
  }

  public void setSelfieImageMimeType(@javax.annotation.Nullable String selfieImageMimeType) {
    this.selfieImageMimeType = JsonNullable.<String>of(selfieImageMimeType);
  }


  /**
   * Return true if this PolandMobywatelMatchInput object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PolandMobywatelMatchInput polandMobywatelMatchInput = (PolandMobywatelMatchInput) o;
    return equalsNullable(this.givenName, polandMobywatelMatchInput.givenName) &&
        equalsNullable(this.familyName, polandMobywatelMatchInput.familyName) &&
        equalsNullable(this.dateOfBirth, polandMobywatelMatchInput.dateOfBirth) &&
        equalsNullable(this.nationality, polandMobywatelMatchInput.nationality) &&
        equalsNullable(this.personalNumber, polandMobywatelMatchInput.personalNumber) &&
        equalsNullable(this.expirationDate, polandMobywatelMatchInput.expirationDate) &&
        equalsNullable(this.selfieBytes, polandMobywatelMatchInput.selfieBytes) &&
        equalsNullable(this.selfieImageMimeType, polandMobywatelMatchInput.selfieImageMimeType);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(givenName), hashCodeNullable(familyName), hashCodeNullable(dateOfBirth), hashCodeNullable(nationality), hashCodeNullable(personalNumber), hashCodeNullable(expirationDate), hashCodeNullable(selfieBytes), hashCodeNullable(selfieImageMimeType));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PolandMobywatelMatchInput {\n");
    sb.append("    givenName: ").append(toIndentedString(givenName)).append("\n");
    sb.append("    familyName: ").append(toIndentedString(familyName)).append("\n");
    sb.append("    dateOfBirth: ").append(toIndentedString(dateOfBirth)).append("\n");
    sb.append("    nationality: ").append(toIndentedString(nationality)).append("\n");
    sb.append("    personalNumber: ").append(toIndentedString(personalNumber)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    selfieBytes: ").append(toIndentedString(selfieBytes)).append("\n");
    sb.append("    selfieImageMimeType: ").append(toIndentedString(selfieImageMimeType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `givenName` to the URL query string
    if (getGivenName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgivenName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGivenName()))));
    }

    // add `familyName` to the URL query string
    if (getFamilyName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfamilyName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFamilyName()))));
    }

    // add `dateOfBirth` to the URL query string
    if (getDateOfBirth() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdateOfBirth%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDateOfBirth()))));
    }

    // add `nationality` to the URL query string
    if (getNationality() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snationality%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNationality()))));
    }

    // add `personalNumber` to the URL query string
    if (getPersonalNumber() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spersonalNumber%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPersonalNumber()))));
    }

    // add `expirationDate` to the URL query string
    if (getExpirationDate() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexpirationDate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpirationDate()))));
    }

    // add `selfieBytes` to the URL query string
    if (getSelfieBytes() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sselfieBytes%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSelfieBytes()))));
    }

    // add `selfieImageMimeType` to the URL query string
    if (getSelfieImageMimeType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sselfieImageMimeType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSelfieImageMimeType()))));
    }

    return joiner.toString();
  }
}

