/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.trinsic.api.models.FaydaProviderOutput;
import id.trinsic.api.models.MexicoCurpProviderOutput;
import id.trinsic.api.models.PhilippinesDigitalNidProviderOutput;
import id.trinsic.api.models.PhilippinesPhysicalNidProviderOutput;
import id.trinsic.api.models.SpidProviderOutput;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import id.trinsic.ApiClient;
/**
 * ProviderOutput
 */
@JsonPropertyOrder({
  ProviderOutput.JSON_PROPERTY_ITALY_SPID,
  ProviderOutput.JSON_PROPERTY_MEXICO_CURP_LOOKUP,
  ProviderOutput.JSON_PROPERTY_ETHIOPIA_FAYDA,
  ProviderOutput.JSON_PROPERTY_PHILIPPINES_PHYSICAL_NATIONAL_ID_QR,
  ProviderOutput.JSON_PROPERTY_PHILIPPINES_DIGITAL_NATIONAL_ID_QR
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-19T23:40:27.630088627Z[Etc/UTC]", comments = "Generator version: 7.13.0")
public class ProviderOutput {
  public static final String JSON_PROPERTY_ITALY_SPID = "italy-spid";
  private JsonNullable<SpidProviderOutput> italySpid = JsonNullable.<SpidProviderOutput>undefined();

  public static final String JSON_PROPERTY_MEXICO_CURP_LOOKUP = "mexico-curp-lookup";
  private JsonNullable<MexicoCurpProviderOutput> mexicoCurpLookup = JsonNullable.<MexicoCurpProviderOutput>undefined();

  public static final String JSON_PROPERTY_ETHIOPIA_FAYDA = "ethiopia-fayda";
  private JsonNullable<FaydaProviderOutput> ethiopiaFayda = JsonNullable.<FaydaProviderOutput>undefined();

  public static final String JSON_PROPERTY_PHILIPPINES_PHYSICAL_NATIONAL_ID_QR = "philippines-physical-national-id-qr";
  private JsonNullable<PhilippinesPhysicalNidProviderOutput> philippinesPhysicalNationalIdQr = JsonNullable.<PhilippinesPhysicalNidProviderOutput>undefined();

  public static final String JSON_PROPERTY_PHILIPPINES_DIGITAL_NATIONAL_ID_QR = "philippines-digital-national-id-qr";
  private JsonNullable<PhilippinesDigitalNidProviderOutput> philippinesDigitalNationalIdQr = JsonNullable.<PhilippinesDigitalNidProviderOutput>undefined();

  public ProviderOutput() { 
  }

  public ProviderOutput italySpid(@javax.annotation.Nullable SpidProviderOutput italySpid) {
    this.italySpid = JsonNullable.<SpidProviderOutput>of(italySpid);
    return this;
  }

  /**
   * Get italySpid
   * @return italySpid
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public SpidProviderOutput getItalySpid() {
        return italySpid.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ITALY_SPID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<SpidProviderOutput> getItalySpid_JsonNullable() {
    return italySpid;
  }
  
  @JsonProperty(JSON_PROPERTY_ITALY_SPID)
  public void setItalySpid_JsonNullable(JsonNullable<SpidProviderOutput> italySpid) {
    this.italySpid = italySpid;
  }

  public void setItalySpid(@javax.annotation.Nullable SpidProviderOutput italySpid) {
    this.italySpid = JsonNullable.<SpidProviderOutput>of(italySpid);
  }


  public ProviderOutput mexicoCurpLookup(@javax.annotation.Nullable MexicoCurpProviderOutput mexicoCurpLookup) {
    this.mexicoCurpLookup = JsonNullable.<MexicoCurpProviderOutput>of(mexicoCurpLookup);
    return this;
  }

  /**
   * Get mexicoCurpLookup
   * @return mexicoCurpLookup
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public MexicoCurpProviderOutput getMexicoCurpLookup() {
        return mexicoCurpLookup.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_MEXICO_CURP_LOOKUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<MexicoCurpProviderOutput> getMexicoCurpLookup_JsonNullable() {
    return mexicoCurpLookup;
  }
  
  @JsonProperty(JSON_PROPERTY_MEXICO_CURP_LOOKUP)
  public void setMexicoCurpLookup_JsonNullable(JsonNullable<MexicoCurpProviderOutput> mexicoCurpLookup) {
    this.mexicoCurpLookup = mexicoCurpLookup;
  }

  public void setMexicoCurpLookup(@javax.annotation.Nullable MexicoCurpProviderOutput mexicoCurpLookup) {
    this.mexicoCurpLookup = JsonNullable.<MexicoCurpProviderOutput>of(mexicoCurpLookup);
  }


  public ProviderOutput ethiopiaFayda(@javax.annotation.Nullable FaydaProviderOutput ethiopiaFayda) {
    this.ethiopiaFayda = JsonNullable.<FaydaProviderOutput>of(ethiopiaFayda);
    return this;
  }

  /**
   * Get ethiopiaFayda
   * @return ethiopiaFayda
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public FaydaProviderOutput getEthiopiaFayda() {
        return ethiopiaFayda.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ETHIOPIA_FAYDA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<FaydaProviderOutput> getEthiopiaFayda_JsonNullable() {
    return ethiopiaFayda;
  }
  
  @JsonProperty(JSON_PROPERTY_ETHIOPIA_FAYDA)
  public void setEthiopiaFayda_JsonNullable(JsonNullable<FaydaProviderOutput> ethiopiaFayda) {
    this.ethiopiaFayda = ethiopiaFayda;
  }

  public void setEthiopiaFayda(@javax.annotation.Nullable FaydaProviderOutput ethiopiaFayda) {
    this.ethiopiaFayda = JsonNullable.<FaydaProviderOutput>of(ethiopiaFayda);
  }


  public ProviderOutput philippinesPhysicalNationalIdQr(@javax.annotation.Nullable PhilippinesPhysicalNidProviderOutput philippinesPhysicalNationalIdQr) {
    this.philippinesPhysicalNationalIdQr = JsonNullable.<PhilippinesPhysicalNidProviderOutput>of(philippinesPhysicalNationalIdQr);
    return this;
  }

  /**
   * Get philippinesPhysicalNationalIdQr
   * @return philippinesPhysicalNationalIdQr
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public PhilippinesPhysicalNidProviderOutput getPhilippinesPhysicalNationalIdQr() {
        return philippinesPhysicalNationalIdQr.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PHILIPPINES_PHYSICAL_NATIONAL_ID_QR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<PhilippinesPhysicalNidProviderOutput> getPhilippinesPhysicalNationalIdQr_JsonNullable() {
    return philippinesPhysicalNationalIdQr;
  }
  
  @JsonProperty(JSON_PROPERTY_PHILIPPINES_PHYSICAL_NATIONAL_ID_QR)
  public void setPhilippinesPhysicalNationalIdQr_JsonNullable(JsonNullable<PhilippinesPhysicalNidProviderOutput> philippinesPhysicalNationalIdQr) {
    this.philippinesPhysicalNationalIdQr = philippinesPhysicalNationalIdQr;
  }

  public void setPhilippinesPhysicalNationalIdQr(@javax.annotation.Nullable PhilippinesPhysicalNidProviderOutput philippinesPhysicalNationalIdQr) {
    this.philippinesPhysicalNationalIdQr = JsonNullable.<PhilippinesPhysicalNidProviderOutput>of(philippinesPhysicalNationalIdQr);
  }


  public ProviderOutput philippinesDigitalNationalIdQr(@javax.annotation.Nullable PhilippinesDigitalNidProviderOutput philippinesDigitalNationalIdQr) {
    this.philippinesDigitalNationalIdQr = JsonNullable.<PhilippinesDigitalNidProviderOutput>of(philippinesDigitalNationalIdQr);
    return this;
  }

  /**
   * Get philippinesDigitalNationalIdQr
   * @return philippinesDigitalNationalIdQr
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public PhilippinesDigitalNidProviderOutput getPhilippinesDigitalNationalIdQr() {
        return philippinesDigitalNationalIdQr.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PHILIPPINES_DIGITAL_NATIONAL_ID_QR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<PhilippinesDigitalNidProviderOutput> getPhilippinesDigitalNationalIdQr_JsonNullable() {
    return philippinesDigitalNationalIdQr;
  }
  
  @JsonProperty(JSON_PROPERTY_PHILIPPINES_DIGITAL_NATIONAL_ID_QR)
  public void setPhilippinesDigitalNationalIdQr_JsonNullable(JsonNullable<PhilippinesDigitalNidProviderOutput> philippinesDigitalNationalIdQr) {
    this.philippinesDigitalNationalIdQr = philippinesDigitalNationalIdQr;
  }

  public void setPhilippinesDigitalNationalIdQr(@javax.annotation.Nullable PhilippinesDigitalNidProviderOutput philippinesDigitalNationalIdQr) {
    this.philippinesDigitalNationalIdQr = JsonNullable.<PhilippinesDigitalNidProviderOutput>of(philippinesDigitalNationalIdQr);
  }


  /**
   * Return true if this ProviderOutput object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProviderOutput providerOutput = (ProviderOutput) o;
    return equalsNullable(this.italySpid, providerOutput.italySpid) &&
        equalsNullable(this.mexicoCurpLookup, providerOutput.mexicoCurpLookup) &&
        equalsNullable(this.ethiopiaFayda, providerOutput.ethiopiaFayda) &&
        equalsNullable(this.philippinesPhysicalNationalIdQr, providerOutput.philippinesPhysicalNationalIdQr) &&
        equalsNullable(this.philippinesDigitalNationalIdQr, providerOutput.philippinesDigitalNationalIdQr);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(italySpid), hashCodeNullable(mexicoCurpLookup), hashCodeNullable(ethiopiaFayda), hashCodeNullable(philippinesPhysicalNationalIdQr), hashCodeNullable(philippinesDigitalNationalIdQr));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProviderOutput {\n");
    sb.append("    italySpid: ").append(toIndentedString(italySpid)).append("\n");
    sb.append("    mexicoCurpLookup: ").append(toIndentedString(mexicoCurpLookup)).append("\n");
    sb.append("    ethiopiaFayda: ").append(toIndentedString(ethiopiaFayda)).append("\n");
    sb.append("    philippinesPhysicalNationalIdQr: ").append(toIndentedString(philippinesPhysicalNationalIdQr)).append("\n");
    sb.append("    philippinesDigitalNationalIdQr: ").append(toIndentedString(philippinesDigitalNationalIdQr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `italy-spid` to the URL query string
    if (getItalySpid() != null) {
      joiner.add(getItalySpid().toUrlQueryString(prefix + "italy-spid" + suffix));
    }

    // add `mexico-curp-lookup` to the URL query string
    if (getMexicoCurpLookup() != null) {
      joiner.add(getMexicoCurpLookup().toUrlQueryString(prefix + "mexico-curp-lookup" + suffix));
    }

    // add `ethiopia-fayda` to the URL query string
    if (getEthiopiaFayda() != null) {
      joiner.add(getEthiopiaFayda().toUrlQueryString(prefix + "ethiopia-fayda" + suffix));
    }

    // add `philippines-physical-national-id-qr` to the URL query string
    if (getPhilippinesPhysicalNationalIdQr() != null) {
      joiner.add(getPhilippinesPhysicalNationalIdQr().toUrlQueryString(prefix + "philippines-physical-national-id-qr" + suffix));
    }

    // add `philippines-digital-national-id-qr` to the URL query string
    if (getPhilippinesDigitalNationalIdQr() != null) {
      joiner.add(getPhilippinesDigitalNationalIdQr().toUrlQueryString(prefix + "philippines-digital-national-id-qr" + suffix));
    }

    return joiner.toString();
  }
}

