/*
 * Trinsic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package id.trinsic.api.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import id.trinsic.api.models.SubProviderMetadata;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import id.trinsic.ApiClient;
/**
 * RecommendProviderInformation
 */
@JsonPropertyOrder({
  RecommendProviderInformation.JSON_PROPERTY_ID,
  RecommendProviderInformation.JSON_PROPERTY_NAME,
  RecommendProviderInformation.JSON_PROPERTY_LOGO_URL,
  RecommendProviderInformation.JSON_PROPERTY_SUBTEXT,
  RecommendProviderInformation.JSON_PROPERTY_HEALTH,
  RecommendProviderInformation.JSON_PROPERTY_SUB_PROVIDERS,
  RecommendProviderInformation.JSON_PROPERTY_REGIONS,
  RecommendProviderInformation.JSON_PROPERTY_COUNTRIES,
  RecommendProviderInformation.JSON_PROPERTY_SUBDIVISIONS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-30T21:52:08.212657203Z[Etc/UTC]", comments = "Generator version: 7.13.0")
public class RecommendProviderInformation {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_LOGO_URL = "logoUrl";
  @javax.annotation.Nonnull
  private String logoUrl;

  public static final String JSON_PROPERTY_SUBTEXT = "subtext";
  @javax.annotation.Nonnull
  private String subtext;

  public static final String JSON_PROPERTY_HEALTH = "health";
  @javax.annotation.Nonnull
  private String health;

  public static final String JSON_PROPERTY_SUB_PROVIDERS = "subProviders";
  private JsonNullable<List<SubProviderMetadata>> subProviders = JsonNullable.<List<SubProviderMetadata>>undefined();

  public static final String JSON_PROPERTY_REGIONS = "regions";
  @javax.annotation.Nonnull
  private List<String> regions = new ArrayList<>();

  public static final String JSON_PROPERTY_COUNTRIES = "countries";
  @javax.annotation.Nonnull
  private List<String> countries = new ArrayList<>();

  public static final String JSON_PROPERTY_SUBDIVISIONS = "subdivisions";
  @javax.annotation.Nonnull
  private List<String> subdivisions = new ArrayList<>();

  public RecommendProviderInformation() { 
  }

  @JsonCreator
  public RecommendProviderInformation(
    @JsonProperty(JSON_PROPERTY_ID) String id, 
    @JsonProperty(JSON_PROPERTY_NAME) String name, 
    @JsonProperty(JSON_PROPERTY_LOGO_URL) String logoUrl, 
    @JsonProperty(JSON_PROPERTY_SUBTEXT) String subtext, 
    @JsonProperty(JSON_PROPERTY_HEALTH) String health, 
    @JsonProperty(JSON_PROPERTY_REGIONS) List<String> regions, 
    @JsonProperty(JSON_PROPERTY_COUNTRIES) List<String> countries, 
    @JsonProperty(JSON_PROPERTY_SUBDIVISIONS) List<String> subdivisions
  ) {
  this();
    this.id = id;
    this.name = name;
    this.logoUrl = logoUrl;
    this.subtext = subtext;
    this.health = health;
    this.regions = regions;
    this.countries = countries;
    this.subdivisions = subdivisions;
  }

  /**
   * The ID of the provider
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }




  /**
   * The friendly, human-readable name of the provider
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }




  /**
   * A URL pointing to the provider&#39;s logo
   * @return logoUrl
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOGO_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getLogoUrl() {
    return logoUrl;
  }




  /**
   * The Provider&#39;s subtext recommended to be shown next to the name.              This is flavor text, not a full, human-readable description of the provider.
   * @return subtext
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUBTEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSubtext() {
    return subtext;
  }




  /**
   * The current health status of the provider
   * @return health
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_HEALTH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getHealth() {
    return health;
  }




  public RecommendProviderInformation subProviders(@javax.annotation.Nullable List<SubProviderMetadata> subProviders) {
    this.subProviders = JsonNullable.<List<SubProviderMetadata>>of(subProviders);
    return this;
  }

  public RecommendProviderInformation addSubProvidersItem(SubProviderMetadata subProvidersItem) {
    if (this.subProviders == null || !this.subProviders.isPresent()) {
      this.subProviders = JsonNullable.<List<SubProviderMetadata>>of(new ArrayList<>());
    }
    try {
      this.subProviders.get().add(subProvidersItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Metadata about the sub-providers which are available for this Provider.              For example, Italy&#39;s SPID is a Provider which aggregates access to multiple sub-providers.
   * @return subProviders
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public List<SubProviderMetadata> getSubProviders() {
        return subProviders.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SUB_PROVIDERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<SubProviderMetadata>> getSubProviders_JsonNullable() {
    return subProviders;
  }
  
  @JsonProperty(JSON_PROPERTY_SUB_PROVIDERS)
  public void setSubProviders_JsonNullable(JsonNullable<List<SubProviderMetadata>> subProviders) {
    this.subProviders = subProviders;
  }

  public void setSubProviders(@javax.annotation.Nullable List<SubProviderMetadata> subProviders) {
    this.subProviders = JsonNullable.<List<SubProviderMetadata>>of(subProviders);
  }


  /**
   * The regions a provider is available in.
   * @return regions
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REGIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getRegions() {
    return regions;
  }




  /**
   * A list of countries, in alpha-2 ISO 3166-1 format, that the provider is available in.
   * @return countries
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COUNTRIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getCountries() {
    return countries;
  }




  /**
   * A list of subdivisions, in ISO 3166-2 format, that the provider is available in.
   * @return subdivisions
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUBDIVISIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getSubdivisions() {
    return subdivisions;
  }




  /**
   * Return true if this RecommendProviderInformation object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecommendProviderInformation recommendProviderInformation = (RecommendProviderInformation) o;
    return Objects.equals(this.id, recommendProviderInformation.id) &&
        Objects.equals(this.name, recommendProviderInformation.name) &&
        Objects.equals(this.logoUrl, recommendProviderInformation.logoUrl) &&
        Objects.equals(this.subtext, recommendProviderInformation.subtext) &&
        Objects.equals(this.health, recommendProviderInformation.health) &&
        equalsNullable(this.subProviders, recommendProviderInformation.subProviders) &&
        Objects.equals(this.regions, recommendProviderInformation.regions) &&
        Objects.equals(this.countries, recommendProviderInformation.countries) &&
        Objects.equals(this.subdivisions, recommendProviderInformation.subdivisions);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, logoUrl, subtext, health, hashCodeNullable(subProviders), regions, countries, subdivisions);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecommendProviderInformation {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    logoUrl: ").append(toIndentedString(logoUrl)).append("\n");
    sb.append("    subtext: ").append(toIndentedString(subtext)).append("\n");
    sb.append("    health: ").append(toIndentedString(health)).append("\n");
    sb.append("    subProviders: ").append(toIndentedString(subProviders)).append("\n");
    sb.append("    regions: ").append(toIndentedString(regions)).append("\n");
    sb.append("    countries: ").append(toIndentedString(countries)).append("\n");
    sb.append("    subdivisions: ").append(toIndentedString(subdivisions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format("%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `logoUrl` to the URL query string
    if (getLogoUrl() != null) {
      joiner.add(String.format("%slogoUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLogoUrl()))));
    }

    // add `subtext` to the URL query string
    if (getSubtext() != null) {
      joiner.add(String.format("%ssubtext%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubtext()))));
    }

    // add `health` to the URL query string
    if (getHealth() != null) {
      joiner.add(String.format("%shealth%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHealth()))));
    }

    // add `subProviders` to the URL query string
    if (getSubProviders() != null) {
      for (int i = 0; i < getSubProviders().size(); i++) {
        if (getSubProviders().get(i) != null) {
          joiner.add(getSubProviders().get(i).toUrlQueryString(String.format("%ssubProviders%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `regions` to the URL query string
    if (getRegions() != null) {
      for (int i = 0; i < getRegions().size(); i++) {
        joiner.add(String.format("%sregions%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getRegions().get(i)))));
      }
    }

    // add `countries` to the URL query string
    if (getCountries() != null) {
      for (int i = 0; i < getCountries().size(); i++) {
        joiner.add(String.format("%scountries%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getCountries().get(i)))));
      }
    }

    // add `subdivisions` to the URL query string
    if (getSubdivisions() != null) {
      for (int i = 0; i < getSubdivisions().size(); i++) {
        joiner.add(String.format("%ssubdivisions%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getSubdivisions().get(i)))));
      }
    }

    return joiner.toString();
  }
}

